### ISSUE TITLE
DB error 1406 - data too long for column 'preview'

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#10353]
- [X] I have searched open and closed issues for duplicates

### Bug Description

Looks like the `preview` column is too short to store the URL. Length of the URL 324 characters. I guess - w/o checking ;-) - the column has a length of 256 characters.

Dunno if this is bad. I guess we cannot store and display the preview in these cases.

URLs are often pretty long these days. It's a bad habit. But we should handle this issue somehow. Maybe we should make URL columns 1024 characters long.

```
worker [ERROR]: DB Error {"code":1406,"error":"Data too long for column 'preview' at row 1","callstack":"Media::insert, twitter_store_attachments, twitter_createpost, twitter_fetchhometimeline, twitter_sync_run, Worker::execFunction, Worker::execute, Worker::processQueue","params":"INSERT INTO `post-media` (`uri-id`, `type`, `url`, `name`, `mimetype`, `size`, `preview`, `preview-height`, `preview-width`, `description`, `author-url`, `author-name`, `author-image`, `publisher-url`, `publisher-name`, `publisher-image`) VALUES (49602869, 17, 'https:\/\/www.theguardian.com\/environment\/2021\/jun\/02\/scientists-propose-urgent-824m-mission-to-document-australias-undiscovered-plants-and-animals?CMP=twt_a-environment_b-gdneco', 'Scientists propose urgent $824m mission to document Australia\u2019s undiscovered plants and animals', 'text\/html; charset=UTF-8', 46142, 'https:\/\/i.guim.co.uk\/img\/media\/98cd51de97c22ff6038868f9295dfcb78e2f1e25\/0_0_6720_4032\/master\/6720.jpg?width=1200&height=630&quality=85&auto=format&fit=crop&overlay-align=bottom%2Cleft&overlay-width=100p&overlay-base64=L2ltZy9zdGF0aWMvb3ZlcmxheXMvdGctZGVmYXVsdC5wbmc&enable=upscale&s=d9a09e92d91f5b72815c2653ce778d6a', 630, 1200, 'Climate crisis makes mammoth task of recording all of Australia\u2019s species over the next 25 years critical, academy says', 'https:\/\/www.theguardian.com\/profile\/graham-readfearn', 'Graham Readfearn', NULL, 'https:\/\/www.theguardian.com\/', 'The Guardian', 'https:\/\/uploads.guim.co.uk\/2018\/01\/31\/TheGuardian_AMP.png') ON DUPLICATE KEY UPDATE `uri-id` = 49602869, `type` = 17, `url` = 'https:\/\/www.theguardian.com\/environment\/2021\/jun\/02\/scientists-propose-urgent-824m-mission-to-document-australias-undiscovered-plants-and-animals?CMP=twt_a-environment_b-gdneco', `name` = 'Scientists propose urgent $824m mission to document Australia\u2019s undiscovered plants and animals', `mimetype` = 'text\/html; charset=UTF-8', `size` = 46142, `preview` = 'https:\/\/i.guim.co.uk\/img\/media\/98cd51de97c22ff6038868f9295dfcb78e2f1e25\/0_0_6720_4032\/master\/6720.jpg?width=1200&height=630&quality=85&auto=format&fit=crop&overlay-align=bottom%2Cleft&overlay-width=100p&overlay-base64=L2ltZy9zdGF0aWMvb3ZlcmxheXMvdGctZGVmYXVsdC5wbmc&enable=upscale&s=d9a09e92d91f5b72815c2653ce778d6a', `preview-height` = 630, `preview-width` = 1200, `description` = 'Climate crisis makes mammoth task of recording all of Australia\u2019s species over the next 25 years critical, academy says', `author-url` = 'https:\/\/www.theguardian.com\/profile\/graham-readfearn', `author-name` = 'Graham Readfearn', `author-image` = NULL, `publisher-url` = 'https:\/\/www.theguardian.com\/', `publisher-name` = 'The Guardian', `publisher-image` = 'https:\/\/uploads.guim.co.uk\/2018\/01\/31\/TheGuardian_AMP.png'"} - {"file":"Database.php","line":765,"function":"e","uid":"6dbc49","process_id":3051805}
```

### Platform Info

Friendica Version:
2021.06-rc

Friendica Source: 
git

PHP version:
7.4

SQL version:
10.3 MariaDB

**Comment by MrPetovan** [comment]
If we aren't doing any indexing on this, we could switch to a text field type.

**Comment by annando** [comment]
We should be able increasing the field to about 511 - like the `url` field in that table. It's good that this field is a `varbinary`. This means that a 511 byte long `varbinary` field will need as much space as a 128 byte long `varchar`.

**Comment by fabrixxm** [comment]
I've got a similar error:

File | Line | Function 
-- | -- | -- 
Database.php | 766 | e 


**Data too long for column 'k' at row 1**
```
callstack:
Media::insert, Processor::storeAttachmentAsMedia, Processor::storeAttachments, Processor::createItem, Receiver::processActivity, Receiver::processInbox, Inbox::rawContent, call_user_func

params:
REPLACE `cache` (`k`, `v`, `expires`, `updated`) VALUES ('https://botusercontent.telegra.ph/ifttt/file/eyJmIjoiQWdBQ0FnUUFBeDBDVWJRMmRBQUNYRUpoZ1VHdllBdVJZQVVYeXU0d190N1lrMlBDM2dBQ1JhMHhHX0x4REZBWTBaX2NrQnhIV3dFQUF3SUFBM2tBQXlFRSIsIm0iOiJpbWFnZVwvanBlZyIsIm4iOiJwaG90by5qcGciLCJkIjoxNjM1ODYwOTEyfQ/8c78e7d4cc5abedf22/photo.jpg', 'a:8:{i:0;i:768;i:1;i:1024;i:2;i:2;i:3;s:25:\"width=\"768\" height=\"1024\"\";s:4:\"bits\";i:8;s:8:\"channels\";i:3;s:4:\"mime\";s:10:\"image/jpeg\";s:4:\"size\";i:133072;}', '2021-11-02 13:55:12', '2021-11-02 13:50:12')
```
(I need to implement a "copy as a plain text" in logs viewer :D )

Moved to https://github.com/friendica/friendica/issues/11248

**Comment by urbalazs** [comment]
I link this issue to the others [here](https://github.com/friendica/friendica/issues/11217#issuecomment-1035942954).

**Comment by MrPetovan** [comment]
Thanks for the report, we should use a hash of the URL for the cache key in the media context.

**Comment by bkil** [comment]
Yes, an URL can be up to 8kB without the anchor/fragment, and then that can be practically unbounded. Some browsers impose arbitrary limits ~2kB, though.

https://github.com/bkil/private-plugin.php#user-content-server-side-uri-length-limit

Imposing a 255 character hard limit that isn't even communicated on the user interface doesn't sound ideal, though.

Note that if this cap was designed to please indexing as you mentioned, it would probably only apply to utf8mb3 - it could already be potentially up to 1020 bytes in utf8mb4. But I think that limitation was solved quite some years ago.

**Comment by ne20002** [comment]
With version 2022.3 I still have this error.

At Database.php line 782.

e.g.:

```
error:
Data too long for column 'url' at row 1

callstack:
Media::insert, Processor::storeAttachmentAsMedia, Processor::storeAttachments, Processor::createItem, Receiver::processActivity, Receiver::processInbox, Inbox::rawContent, BaseModule::run

params:
INSERT INTO `post-media` (`uri-id`, `type`, `url`, `mimetype`, `height`) VALUES (36924, 16, 'magnet:?xs=https%3A%2F%2Ftilvids.com%2Flazy-static%2Ftorrents%2Fbe8259be-813c-40d4-a160-b6910ed43552-1080-hls.torrent&xt=urn:btih:d93832e5a4d2863999876e20ce95683830a6ad3d&dn=Krita+%22Photoshopping%22+-+How+I+Made+This+Isometric+Mini+World+in+Krita+Using+CC+Photos+%26+Images&tr=https%3A%2F%2Ftilvids.com%2Ftracker%2Fannounce&tr=wss%3A%2F%2Ftilvids.com%3A443%2Ftracker%2Fsocket&ws=https%3A%2F%2Ftilvids.com%2Fstatic%2Fstreaming-playlists%2Fhls%2Fe2bc3792-0d65-4fdc-8eea-d4b2b7f2496b%2F7e13e003-52b3-444c-aa50-375556f842f9-1080-fragmented.mp4', 'application/x-bittorrent;x-scheme-handler/magnet', 1080) ON DUPLICATE KEY UPDATE `uri-id` = 36924, `type` = 16, `url` = 'magnet:?xs=https%3A%2F%2Ftilvids.com%2Flazy-static%2Ftorrents%2Fbe8259be-813c-40d4-a160-b6910ed43552-1080-hls.torrent&xt=urn:btih:d93832e5a4d2863999876e20ce95683830a6ad3d&dn=Krita+%22Photoshopping%22+-+How+I+Made+This+Isometric+Mini+World+in+Krita+Using+CC+Photos+%26+Images&tr=https%3A%2F%2Ftilvids.com%2Ftracker%2Fannounce&tr=wss%3A%2F%2Ftilvids.com%3A443%2Ftracker%2Fsocket&ws=https%3A%2F%2Ftilvids.com%2Fstatic%2Fstreaming-playlists%2Fhls%2Fe2bc3792-0d65-4fdc-8eea-d4b2b7f2496b%2F7e13e003-52b3-444c-aa50-375556f842f9-1080-fragmented.mp4', `mimetype` = 'application/x-bittorrent;x-scheme-handler/magnet', `height` = 1080
```

**Comment by MrPetovan** [comment]
Thank you for the report, we haven't changed the column type yet, so the error is bound to come up again.

**Comment by urbalazs** [comment]
This is still an issue in Friendica 2022.06, from the log:

```
[ERROR]: DB Error {
    "code": 1406,
    "error": "Data too long for column 'preview' at row 1",
    "callstack": "Item::insert, Processor::postItem, Receiver::processActivity, Processor::fetchMissingActivity, Item::fetchByLink, Processor::fetchFeaturedPosts, FetchFeaturedPosts::execute, Worker::execFunction",
    "params": "INSERT INTO `post-media` (`uri-id`, `type`, `url`, `mimetype`, `size`, `preview`, `preview-height`, `preview-width`, `description`, `name`, `author-url`, `author-name`, `author-image`, `publisher-url`, `publisher-name`, `publisher-image`) VALUES (80208, 17, 'https://t.me/MutualSympathyBot', 'text/html; charset=utf-8', 10714, 'https://cdn5.telegram-cdn.org/file/kd11Ml5RI2MrqNHML-0Jap1mynljeo-eXNkj_us_jP3KplKzvlEQS8mRcryT8zCec6is3U5ic00Dr5MjHdxb3TkWaA9QI4XA74nqCOXxjnthYdcAasqMqNh5-50O_P_HB7bMt7WBcwmfSkcuFlb8LTmduQNKdfh0VQKiNftPE04XjVSAhQXvt2uUZDWu2dpgcO9gOdsopYfEWQI8NT8SfgMwdke__eFwDSTVUZRN90cCMobblJLodxRYaApRLAJFLSEHQG1sdNqhWOkNsbIToWFWXEsSI59DLxymYiViTl4RXUsMREu5E_Fc3xU4aDcgzPx3UXo0v9FvKYQWb6Mlsw.jpg', 320, 320, 'You can contact @MutualSympathyBot right away.', 'Telegram Sympathy Bot', NULL, NULL, NULL, NULL, 'Telegram', NULL) ON DUPLICATE KEY UPDATE `uri-id` = 80208, `type` = 17, `url` = 'https://t.me/MutualSympathyBot', `mimetype` = 'text/html; charset=utf-8', `size` = 10714, `preview` = 'https://cdn5.telegram-cdn.org/file/kd11Ml5RI2MrqNHML-0Jap1mynljeo-eXNkj_us_jP3KplKzvlEQS8mRcryT8zCec6is3U5ic00Dr5MjHdxb3TkWaA9QI4XA74nqCOXxjnthYdcAasqMqNh5-50O_P_HB7bMt7WBcwmfSkcuFlb8LTmduQNKdfh0VQKiNftPE04XjVSAhQXvt2uUZDWu2dpgcO9gOdsopYfEWQI8NT8SfgMwdke__eFwDSTVUZRN90cCMobblJLodxRYaApRLAJFLSEHQG1sdNqhWOkNsbIToWFWXEsSI59DLxymYiViTl4RXUsMREu5E_Fc3xU4aDcgzPx3UXo0v9FvKYQWb6Mlsw.jpg', `preview-height` = 320, `preview-width` = 320, `description` = 'You can contact @MutualSympathyBot right away.', `name` = 'Telegram Sympathy Bot', `author-url` = NULL, `author-name` = NULL, `author-image` = NULL, `publisher-url` = NULL, `publisher-name` = 'Telegram', `publisher-image` = NULL"
} - {
    "file": "Database.php",
    "line": 782,
    "function": "e",
    "uid": "6b9f17",
    "process_id": 69090
}
```

**Comment by Quix0r** [comment]
Getting the same here with some super-long URLs. Can I change it to `text`?

**Comment by MrPetovan** [comment]
Yes, it isn't part of a key. Don't change `url` though.

**Comment by Quix0r** [comment]
Now I'm a bit confused. I changed `post-media.url` to `text` and you have merged it and it did fix the problem?

**Comment by MrPetovan** [comment]
I didn't realize it was the same table. @annando will tell you better than me if it's a problem.

**Comment by Quix0r** [comment]
I found this now: `BLOB/TEXT column 'url' used in key specification without a key length`. I guess I have to fix the SQL file here.

**Comment by Quix0r** [comment]
Looks like I have to build an index like this: `UNIQUE (url(512))`

Edit: My commit 9351821fd9eb9cf3d378fab110fbb311f6bb2ac2 fixes this in PR #11657

**Comment by annando** [comment]
Please don't change it to `text`. See here: https://stackoverflow.com/a/2023945

**Comment by Quix0r** [comment]
The old 511 value was to small for some super-long URLs e.g. as shown in my comment https://github.com/friendica/friendica/issues/10193#issuecomment-1158120448 So you want me to change it back to `varbinary(1024)` or so? Why `varbinary` and not `varchar`? Aren't URLs supposed to be URL-encoded (e.g. `+` or `%20` for a space) to have these "special" characters in them?

**Comment by annando** [comment]
You use `varchar` for content that contains encoded text. And when you - for example - are searching for something with an `a` in it, then the system will possibly also return stuff with an `ä` in it.  An `URL` in difference to this has to be retrieved like it had been stored. It is faster to store and retrieve and it uses a quarter of the size of a comparable `varchar`.

Before increasing the length please have a look in the documentation of the Antelope and the Barracude file format of InnoDB. They have got some maximum key length. So increasing the size could lead to an error on some installations if the limit is reached. I'm currently unsure about the limit, but this is always risky.

**Comment by Quix0r** [comment]
Hmm, yes. Row size maximums may play an important role: https://stackoverflow.com/questions/15585602/change-limit-for-mysql-row-size-too-large

So maybe we are better off here by splitting the table to avoid maximum row size? Like `urls` as a separate table where only URLs and an index (primary key) is being stored in?

**Comment by Quix0r** [comment]
Before I'm reading myself to death (there is to much to read), I'd rather change it to a reasonable size like `varbinary(1024)`. That SHOULD be enough for `magnet:` URLs (and they caused it the most). Plus we need to consider same change for `preview` as some URLs can be super-long there, too.

You can reach my examples of to short `size` and `url` fields here: https://f.haeder.net/db-error.log.txt

Since 511 wasn't enough for `url` and 255 seem not to be enough for `preview` I simply double the values instead of studying MySQL/MariaDB internals.

**Comment by bkil** [comment]
I would like to highlight that there is nothing intrinsically "wrong" with an URI up to 8 kB in length. 2 kB ones should be handled by all servers and clients from the past decades at a minimum. An anchor may make it even longer, but I would consider such a long URI as more of an anomaly (or a clever geeky hack) than a usual thing.

To cope with this, we must ask ourselves what we really want to search for in a URL. According to my observation, in the majority of cases, I usually want to search for either the publisher or the title of the article itself or some keyword metadata provided by the article.

This could ideally be achieved by unfurling the links and indexing the OEmbed metadata (or a prefix of it).

As an alternative, indexing up to a given number of characters of _each part_ of the percentile-decoded URL (protocol and domain, path, query and anchor) might also work with _special_ tokenization. According to my observation, the URI query is usually not helpful, although the anchor might be if it links to a well named subsection for example. Storage-wise, this might also be represented as a new field dedicated for storing the full, untouched URI and only indexing a size-limited field which stores the processed tokens generated from the URI.

**Comment by Quix0r** [comment]
And remember when the first specification of MySQL/MyISAM was written, they were not able to see that one day over-sized `magnet:` URLs will become reality. No body has seen that coming, including 4k/8k or even 16k [sic] videos with sizes beyond `int`. I guess when Friendica wants to stay modern, we have to go with it.

**Comment by bkil** [comment]
I have found and documented various _practical_ limits of URI length in the past (255, 511, 1024, 2047, 2083, 4000, 4043, 4094, 4096, 8190, 8192, 32768), but I have yet to find a definite standard about it. I still consider a system "broken" if it can't cope with a 8k URI as per:

* https://datatracker.ietf.org/doc/html/rfc7230#section-3.1.1

> It is RECOMMENDED that all HTTP senders and recipients support, at a minimum, request-line lengths of 8000 octets.

Even in 1999, they were mostly concerned about an "**older** client or proxy" when they shared their recommendation against _generating_ a long URI, but at the same time, _servers_ were already encouraged to _accept_ long URI back then:

- https://www.rfc-editor.org/rfc/rfc2616#section-3.2.1

>   Note: Servers ought to be cautious about depending on URI lengths above 255 bytes, because some older client or proxy implementations might not properly support these lengths.

And even in their basic form, the protocol and host part (domain name, port) together may already be longer than 255 bytes, and most mainstream file systems in the 90s could handle filenames about 255 byte long already (although, most real use cases map URIs) and those two together pushes it above 500 bytes without anything in the query or fragment at all.

**Comment by MrPetovan** [comment]
I don't think the `url` needs to be in an index to be searchable, but for uniqueness. I'd like to reiterate my suggestion to use a hash of the URL for this purpose with a fixed and manageable length, and have the `url` a text field since we don't need to search on it, just retrieve and display it.

**Comment by Quix0r** [comment]
@MrPetovan That is maybe more performant than having a `TEXT` field and then `WHERE url = ?` on it? Where `?` is a placeholder.

**Comment by Quix0r** [comment]
I think the upgrade is relatively easy:
1) Add column `url_hash`
2) Run through all rows and hash value of `url`
3) Save it in database

I would like to use some SQL hashing function which is easier to implement in an update: `UPDATE post-media SET url_hash=SOME_HASHING(url) WHERE url != '';` or so?

**Comment by MrPetovan** [comment]
The tricky part is that the unique index can only be moved once the hash has been computed. So it needs to be a pre_update method in the `update.php` file so that the DB structure update can correctly move the unique index and change the field type to `text`.

**Comment by Quix0r** [comment]
I have found no issues on my instance by letting the whole SQL statement running, changing column and index at the same time.

**Comment by MrPetovan** [comment]
Even adding a new `url_hash` column that's supposed to be the new unique index?

**Comment by Quix0r** [comment]
Ah, okay. I guess there it will make trouble because the same combination may exist already. Good point!

**Comment by MrPetovan** [comment]
More like because when you create the column, it will initialize the value to NULL and moving the UNIQUE index will fail until the actual values are computed but the spirit is the same.

**Comment by annando** [comment]
@Quix0r 
> Before I'm reading myself to death (there is to much to read), I'd rather change it to a reasonable size like varbinary(1024)

AFAIK for Antelope (the "COMPACT Row Format"), the row size is 768 bytes. So the update process will fail on these systems. Please inform yourself about the consequences of such changes before applying them. Some "Fire&Forget" doesn't work here. We have to consider every reasonable setup and cannot just tell the users: "Sorry that your system doesn't work anymore but I wasn't interested in reading documentations.".

Also - in contrast to code changes - not all database changes can be reverted easily. It had been a multiple year long task to change the database structure to the current stage and to fix the problems of the past. So now every change should be done cautiously.

**Comment by Quix0r** [comment]
That's why I switched to `text` instead of `var<binary|char>(x)` because that only leaves a pointer (so far I read) in the table row to the "blob". Yes, URLs aren't long texts, still it was the best solution I could come up with.

**Comment by Quix0r** [comment]
Maybe I got too lazy due to heat/illness and the JPA ... ;-)

**Comment by annando** [comment]
Problem with `text` is - AFAIK - the reduced performance. Also this is no solution when the field is in any key.

**Comment by Quix0r** [comment]
@annando Yes, of course. A unique key on the URL makes sense as you don't want to store the same URL multiple times. On the other hand, the key might become to big and then you need to increase key cache to get performance back ... :thinking:

**Comment by MrPetovan** [comment]
Can I suggest once more to create a separate field of fixed size that will contain a hash of the URL that can be safely referred in a key or did everyone already get it? 😄

**Comment by Quix0r** [comment]
@MrPetovan And then we can safely use `text` on `url`/`preview`?

**Comment by MrPetovan** [comment]
Yes, that's the whole point! 😊

**Comment by annando** [comment]
Problem is the conversion process. Please don't rush things here. We have to find a solution that doesn't create problems. Everything that needs a pre- and post update will most likely fail on some machines.

**Comment by Quix0r** [comment]
@MrPetovan So you mean that the `pre_update_XXXX()` function creates the column, runs the hashing on `url` and then let the normal database update change the key?

**Comment by MrPetovan** [comment]
I believe this should work but this aspect of Friendica is @annando 's specialty.

**Comment by annando** [comment]
For fields that aren't part in an index we can use a two field solution. Since `text` fields are really low in the performance we should avoid them when possible. So we could add a second `text` field that would be added when the content is too large. We then query the fields via some view that automagically fetched the one or the other field.

Everything in an index is much more complicated. We had a lot of problems with edge cases in the update process from the old `item` to the new `post-*` tables, so that I would like to avoid thing like these.

**Comment by MrPetovan** [comment]
What's the problem with `text` fields written once and used only during data retrieval but not data lookup?

**Comment by annando** [comment]
`text` is slow, `var*` is faster. But I guess the best idea will be to forcefully switch the file format.

**Comment by MrPetovan** [comment]
> `text` is slow, `var*` is faster.

I thought this was an oversimplification, and it turns out it is:
- [InnoDB stores VARCHAR the same way as TEXT](https://www.percona.com/blog/2010/02/09/blob-storage-in-innodb/).
- [MyISAM stores VARCHAR fields with their maximum size when creating in-memory temporary tables](https://nicj.net/mysql-text-vs-varchar-performance/), forcing some of these tables to be written to disk when the total table size with full size fields would be bigger than `tmp_table_size` or `max_heap_table_size` config values.

I rest my case.

**Comment by annando** [comment]
@MrPetovan there are several differences: https://mariadb.com/kb/en/text/

**Comment by MrPetovan** [comment]
I didn't list all the differences, just the ones belying your simplistic claim. Interestingly,
> Starting with [MariaDB 10.4](https://mariadb.com/kb/en/what-is-mariadb-104/), a unique index can be created on a TEXT column.
> 
> Internally, this uses hash indexing to quickly check the values and if a hash collision is found, the actual stored values are compared in order to retain the uniqueness.

The hash solution is what I suggested to do, however I didn't address potential collisions.

**Comment by annando** [comment]
It's easier to enforce a file format that allows larger keys. Adding some hash in a pre update will be more painful.

**Comment by MrPetovan** [comment]
How does the file format support look like, do we have usage data on the required MySQL/MariaDB version to use the larger keys file format?

**Comment by annando** [comment]
There is already the command `bin/console dbstructure toinnodb`.

**Comment by MrPetovan** [comment]
What would be the hard MySQL/MariaDB version dependency with the suggested file format which you haven't mentioned yet?

**Comment by bkil** [comment]
I thought there were plans to support further commonly requested database backends like Postgresql or SQlite. What about those? #699

**Comment by MrPetovan** [comment]
There are, but pretty long term, we have to finish converting legacy code to the Database abstraction, and then there are specific literal queries that may not work depending on the underlying DBMS that we have to find a solution for.

**Comment by Quix0r** [comment]
The benefit to go finally to more database "drivers" like SQLite3 is, that e.g. the unit tests doesn't have to rely on a running MariaDB/MySQL but can run purely without it. It is much easier for a developer to set up. But no worries, so far it is manageable. :-)
