### ISSUE TITLE
[2023.03] PHP Warnings

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#12488]
Please report here any PHP Warning message obtained running the 2022.12 stable or 2022.03-dev versions.

Replaces https://github.com/friendica/friendica/issues/11993

**Comment by ghost** [comment]
`PHP Warning:  Undefined variable $subject in /src/Navigation/Notifications/Repository/Notify.php on line 819`

Addressed in https://github.com/friendica/friendica/pull/12532

**Comment by ghost** [comment]
```
PHP Warning:  Undefined array key "type" in /home/users/meld/www/meld/src/Protocol/DFRN.php on line 310
PHP Warning:  Undefined array key "" in /home/users/meld/www/meld/src/Protocol/DFRN.php on line 310
```
```
PHP Warning:  Undefined array key "network" in /home/users/meld/www/meld/src/Worker/Delivery.php on line 216
```
```
PHP Warning:  Undefined array key "id" in /home/users/meld/www/meld/src/Worker/Delivery.php on line 286
PHP Warning:  Undefined array key "id" in /home/users/meld/www/meld/src/Worker/Delivery.php on line 318
PHP Warning:  Undefined array key "id" in /home/users/meld/www/meld/src/Worker/Delivery.php on line 356
PHP Warning:  Undefined array key "id" in /home/users/meld/www/meld/src/Worker/Delivery.php on line 371
PHP Warning:  Undefined array key "id" in /home/users/meld/www/meld/src/Worker/Delivery.php on line 405
PHP Warning:  Undefined array key "guid" in /home/users/meld/www/meld/src/Worker/Delivery.php on line 405
```
Addressed in https://github.com/friendica/friendica/pull/12533

**Comment by ghost** [comment]
`PHP Warning:  sem_acquire(): Failed to acquire key 0x66031b0c: Identifier removed in /src/Core/Lock/Type/SemaphoreLock.php on line 65`

**Comment by gravity-deleted** [comment]
Version: 2022.12 - 1502 stable

```
WARNING | index | E_WARNING: Trying to access array offset on value of type bool

view/smarty3/compiled/c6/b3/95/c6b3956e42033457e15b98de5fcc064f877d12e4_2.file.wall_thread.tpl.php:305
```
Addressed in https://github.com/friendica/friendica/pull/12533

**Comment by ghost** [comment]
develop

`PHP Warning:  Undefined variable $subject in /src/Navigation/Notifications/Repository/Notify.php on line 819`

Addressed in https://github.com/friendica/friendica/pull/12532

**Comment by nupplaphil** [comment]
```
2022-12-27T16:07:06+01:00	Friendica[1327]: index [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (Invalid DateTime) at position 0 (I): The timezone could not be found in the database [] - {"file":"Logger.php","line":157,"function":"warning","request-id":"5f297a70b4184b85b92917c683fb5d29","uid":"d7e615"}
```

context:
```
2022-12-27T16:07:08+01:00	Friendica[1327]: index [NOTICE]: created item {"post-id":3918274,"uid":699,"network":"apub","uri-id":3597978,"guid":"62f2bb0c-44c0f878cd90c0ee-dcb54b11"} - {"file":"Logger.php","line":171,"function":"notice","request-id":"5f297a70b4184b85b92917c683fb5d29","uid":"d7e615"}
2022-12-27T16:07:08+01:00	Friendica[1327]: index [NOTICE]: created item {"post-id":3918272,"uid":0,"network":"apub","uri-id":3597978,"guid":"62f2bb0c-44c0f878cd90c0ee-dcb54b11"} - {"file":"Logger.php","line":171,"function":"notice","request-id":"5f297a70b4184b85b92917c683fb5d29","uid":"d7e615"}
2022-12-27T16:07:06+01:00	Friendica[1327]: index [NOTICE]: Curl redirect. {"url":"https://covid.yanoagenda.com/states/New%20York","to":"https://covid.yanoagenda.com/states/New%20York/","method":"GET"} - {"file":"HttpClient.php","line":86,"function":"Friendica\\Network\\HTTPClient\\Factory\\{closure}","request-id":"5f297a70b4184b85b92917c683fb5d29","uid":"d7e615"}
2022-12-27T16:07:06+01:00	Friendica[1327]: index [NOTICE]: Curl redirect. {"url":"https://covid.yanoagenda.com/states/New%20York","to":"https://covid.yanoagenda.com/states/New%20York/","method":"HEAD"} - {"file":"HttpClient.php","line":86,"function":"Friendica\\Network\\HTTPClient\\Factory\\{closure}","request-id":"5f297a70b4184b85b92917c683fb5d29","uid":"d7e615"}
2022-12-27T16:07:05+01:00	Friendica[1327]: index [NOTICE]: Activity was not fetchable, aborting. {"url":"https://covid.yanoagenda.com/states/New%20York","uid":0} - {"file":"Logger.php","line":171,"function":"notice","request-id":"5f297a70b4184b85b92917c683fb5d29","uid":"d7e615"}
2022-12-27T16:07:05+01:00	Friendica[1327]: index [NOTICE]: Curl redirect. {"url":"https://covid.yanoagenda.com/states/New%20York","to":"https://covid.yanoagenda.com/states/New%20York/","method":"GET"} - {"file":"HttpClient.php","line":86,"function":"Friendica\\Network\\HTTPClient\\Factory\\{closure}","request-id":"5f297a70b4184b85b92917c683fb5d29","uid":"d7e615"}
2022-12-27T16:07:04+01:00	Friendica[1327]: index [NOTICE]: Curl redirect. {"url":"https://covid.yanoagenda.com/states/New%20York","to":"https://covid.yanoagenda.com/states/New%20York/","method":"HEAD"} - {"file":"HttpClient.php","line":86,"function":"Friendica\\Network\\HTTPClient\\Factory\\{closure}","request-id":"5f297a70b4184b85b92917c683fb5d29","uid":"d7e615"}
2022-12-27T16:07:01+01:00	Friendica[1327]: index [NOTICE]: LD-verify {"verified":1,"actor":"https://mastodon.cloud/users/covid_stats"} - {"file":"Logger.php","line":171,"function":"notice","request-id":"5f297a70b4184b85b92917c683fb5d29","uid":"d7e615"}
```

**Comment by MrPetovan** [comment]
```
{"file":"Logger.php","line":157,"function":"warning","request-id":"5f297a70b4184b85b92917c683fb5d29","uid":"d7e615"}
```
The context doesn't show where the `DateTimeFormat::convert` method was called from anymore (see https://github.com/friendica/friendica/issues/12550), please address the issue before resubmitting this warning message.

**Comment by utzer** [comment]
```
      7  PHP Warning:  Attempt to read property "blogs" on null in /var/www/addon/tumblr/tumblr.php on line 223
      7  PHP Warning:  Attempt to read property "user" on array in /var/www/addon/tumblr/tumblr.php on line 223
      1  PHP Warning:  iconv(): Wrong encoding, conversion from &quot;utf&quot; to &quot;UTF-8//TRANSLIT&quot; is not allowed in /var/www/src/Util/ParseUrl.php on line 313
      1  PHP Warning:  Undefined array key "move" in /var/www/addon/tictac/tictac.php on line 34
      1  PHP Warning:  Undefined variable $handicap in /var/www/addon/tictac/tictac.php on line 53
      1  PHP Warning:  Undefined variable $mefirst in /var/www/addon/tictac/tictac.php on line 53
      1  PHP Warning:  Undefined variable $mine in /var/www/addon/tictac/tictac.php on line 53
      1  PHP Warning:  Undefined variable $o in /var/www/addon/tictac/tictac.php on line 180
      1  PHP Warning:  Undefined variable $o in /var/www/addon/tictac/tictac.php on line 631
      1  PHP Warning:  Undefined variable $yours in /var/www/addon/tictac/tictac.php on line 53
      1  PHP Warning:  Uninitialized string offset 0 in /var/www/addon/nsfw/nsfw.php on line 91
```

PHP: 8.1.13
Current stable

**Comment by ghost** [comment]
```
PHP Warning:  Trying to access array offset on value of type bool in /src/Util/HTTPSignature.php on line 360
PHP Warning:  Trying to access array offset on value of type bool in /src/Util/HTTPSignature.php on line 372
PHP Warning:  Trying to access array offset on value of type bool in /src/Util/HTTPSignature.php on line 373
PHP Warning:  Trying to access array offset on value of type bool in /src/Util/HTTPSignature.php on line 379
```
Addressed in https://github.com/friendica/friendica/pull/12576

**Comment by nupplaphil** [comment]
```
2022-12-30 16:10:11 | Friendica[23455]: worker [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (Fri Dec 30 2022 14:29:10 GMT+0000 (Coordinated Universal Time)) at position 41 (n): Double timezone specification {"worker_id":"4d95fe3","worker_cmd":"twitter_sync_run"} - {"file":"DateTimeFormat.php","line":157,"function":"convert","request-id":"63aeff4951a21","uid":"ad061b"}
```
Addressed in https://github.com/friendica/friendica/pull/12578

**Comment by MrPetovan** [comment]
Sweet mother of mercy.

**Comment by ghost** [comment]
```
PHP Warning:  Undefined array key "network" in /src/Module/Search/Acl.php on line 83
PHP Warning:  Undefined array key "url" in /src/Module/Search/Acl.php on line 84
PHP Warning:  Undefined array key "contact-type" in /src/Module/Search/Acl.php on line 85
```
Addressed in  https://github.com/friendica/friendica/pull/12589

**Comment by nupplaphil** [comment]
> Sweet mother of mercy.

@MrPetovan  Do you want more DateTimeFormat action? ;-)
```
2023-01-01T15:33:45+01:00	Friendica[115999]: worker [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (2022-12-2010T12:00:00.000Z) at position 10 (1): Unexpected character {"worker_id":"e205239","worker_cmd":"twitter_sync_run"} - {"file":"DateTimeFormat.php","line":157,"function":"convert","request-id":"63b199b402d41","uid":"f392a2"}

2023-01-01T15:33:40+01:00	Friendica[52561]: worker [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (2022-12-2010T12:00:00.000Z) at position 10 (1): Unexpected character {"worker_id":"b290ed3","worker_cmd":"twitter_sync_run"} - {"file":"DateTimeFormat.php","line":157,"function":"convert","request-id":"63b199be063ea","uid":"8921eb"}

2023-01-01T13:50:39+01:00	Friendica[50287]: worker [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (Pa, 01/01/2023, 14:15) at position 0 (P): The timezone could not be found in the database {"worker_id":"d835cc2","worker_cmd":"twitter_sync_run"} - {"file":"DateTimeFormat.php","line":157,"function":"convert","request-id":"63b18184711ef","uid":"801b0c"}

2023-01-01T13:50:39+01:00	Friendica[50287]: worker [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (Pa, 01/01/2023, 14:00) at position 0 (P): The timezone could not be found in the database {"worker_id":"d835cc2","worker_cmd":"twitter_sync_run"} - {"file":"DateTimeFormat.php","line":157,"function":"convert","request-id":"63b18184711ef","uid":"801b0c"}

2023-01-01T13:43:37+01:00	Friendica[110401]: worker [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (Pa, 01/01/2023, 14:15) at position 0 (P): The timezone could not be found in the database {"worker_id":"6bd587f","worker_cmd":"twitter_sync_run"} - {"file":"DateTimeFormat.php","line":157,"function":"convert","request-id":"63b17fde1f680","uid":"78c1e8"}

2023-01-01T13:43:37+01:00	Friendica[110401]: worker [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (Pa, 01/01/2023, 14:00) at position 0 (P): The timezone could not be found in the database {"worker_id":"6bd587f","worker_cmd":"twitter_sync_run"} - {"file":"DateTimeFormat.php","line":157,"function":"convert","request-id":"63b17fde1f680","uid":"78c1e8"}

2023-01-01T04:10:30+01:00	Friendica[37467]: index [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (2023-58-01) at position 6 (8): Unexpected character [] - {"file":"DateTimeFormat.php","line":157,"function":"convert","request-id":"f853e78df76feb929730ce44fa3e6c3c","uid":"358dcc"}
```

**Comment by nupplaphil** [comment]
```
Friendica[112390]: index [WARNING]: No fully qualified URL provided {"url":"https","callstack":"Proxy::rawContent, BaseModule::run, App::runFrontend"} - {"file":"System.php","line":494,"function":"externalRedirect","request-id":"f7847f7c8e463e0cc0b2159211d4011c","uid":"dd34db"}
```

route: `/proxy/8756ee59cb27defa865b5cbd62b62cd5.jpg?url=https`

**Comment by MrPetovan** [comment]
> ```
> 2023-01-01T15:33:45+01:00	Friendica[115999]: worker [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (2022-12-2010T12:00:00.000Z) at position 10 (1): Unexpected character {"worker_id":"e205239","worker_cmd":"twitter_sync_run"} - {"file":"DateTimeFormat.php","line":157,"function":"convert","request-id":"63b199b402d41","uid":"f392a2"}
> 2023-01-01T15:33:40+01:00	Friendica[52561]: worker [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (2022-12-2010T12:00:00.000Z) at position 10 (1): Unexpected character {"worker_id":"b290ed3","worker_cmd":"twitter_sync_run"} - {"file":"DateTimeFormat.php","line":157,"function":"convert","request-id":"63b199be063ea","uid":"8921eb"}
> 2023-01-01T04:10:30+01:00	Friendica[37467]: index [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (2023-58-01) at position 6 (8): Unexpected character [] - {"file":"DateTimeFormat.php","line":157,"function":"convert","request-id":"f853e78df76feb929730ce44fa3e6c3c","uid":"358dcc"}
> ```

What do these even mean???

The first two look like a confusion between the Javascript operator for arithmetic addition (+) and the Javascript operator for string concatenation (also +)

But the last one??? 58 isn't even a week number!

We can't recover from these no matter what we do.

**Comment by MrPetovan** [comment]
> ```
> 2023-01-01T13:50:39+01:00	Friendica[50287]: worker [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (Pa, 01/01/2023, 14:15) at position 0 (P): The timezone could not be found in the database {"worker_id":"d835cc2","worker_cmd":"twitter_sync_run"} - {"file":"DateTimeFormat.php","line":157,"function":"convert","request-id":"63b18184711ef","uid":"801b0c"}
> 2023-01-01T13:50:39+01:00	Friendica[50287]: worker [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (Pa, 01/01/2023, 14:00) at position 0 (P): The timezone could not be found in the database {"worker_id":"d835cc2","worker_cmd":"twitter_sync_run"} - {"file":"DateTimeFormat.php","line":157,"function":"convert","request-id":"63b18184711ef","uid":"801b0c"}
> 2023-01-01T13:43:37+01:00	Friendica[110401]: worker [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (Pa, 01/01/2023, 14:15) at position 0 (P): The timezone could not be found in the database {"worker_id":"6bd587f","worker_cmd":"twitter_sync_run"} - {"file":"DateTimeFormat.php","line":157,"function":"convert","request-id":"63b17fde1f680","uid":"78c1e8"}
> 2023-01-01T13:43:37+01:00	Friendica[110401]: worker [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (Pa, 01/01/2023, 14:00) at position 0 (P): The timezone could not be found in the database {"worker_id":"6bd587f","worker_cmd":"twitter_sync_run"} - {"file":"DateTimeFormat.php","line":157,"function":"convert","request-id":"63b17fde1f680","uid":"78c1e8"}
> ```

Please look out for one of these today German time, I'm not sure where the day is supposed to be in the date structure 😅

**Comment by nupplaphil** [comment]
```
2023-01-05T08:40:45+01:00	Friendica[20063]: worker [WARNING]: E_WARNING: Undefined array key "event" {"code":2,"message":"Undefined array key \"event\"","file":"/var/www/html/src/Navigation/Notifications/Repository/Notify.php","line":468} - {"file":"Notify.php","line":468,"function":"createFromArray","request-id":"63b67efbb6c71","uid":"e74557"}
```

context:
```
2023-01-05T08:40:45+01:00	Friendica[20063]: worker [NOTICE]: public_server: cron end {"worker_id":"51a3580","worker_cmd":"ForkHook"} - {"file":"public_server.php","line":99,"function":"public_server_cron","request-id":"63b67efbb6c71","uid":"e74557"}
2023-01-05T08:40:45+01:00	Friendica[20063]: worker [NOTICE]: sending notification email [] - {"file":"Notify.php","line":601,"function":"storeAndSend","request-id":"63b67efbb6c71","uid":"e74557"}
2023-01-05T08:40:45+01:00	Friendica[20063]: worker [WARNING]: E_WARNING: Undefined array key "event" {"code":2,"message":"Undefined array key \"event\"","file":"/var/www/html/src/Navigation/Notifications/Repository/Notify.php","line":468} - {"file":"Notify.php","line":468,"function":"createFromArray","request-id":"63b67efbb6c71","uid":"e74557"}
2023-01-05T08:40:45+01:00	Friendica[20063]: worker [NOTICE]: public_server: cron start {"worker_id":"51a3580","worker_cmd":"ForkHook"} - {"file":"public_server.php","line":51,"function":"public_server_cron","request-id":"63b67efbb6c71","uid":"e74557"}
```
Addressed in https://github.com/friendica/friendica-addons/pull/1348

**Comment by nupplaphil** [comment]
```
2023-01-05 05:58:170	Friendica[6914]: worker [WARNING]: Unable to insert inbox-status row {"url":"https://dabr.ca/inbox","uri-id":6509407,"created":"2023-01-05 04:58:17","shared":true,"gsid":184411,"worker_id":"6bed207","worker_cmd":"AddContact"} - {"file":"HTTPSignature.php","line":351,"function":"setInboxStatus","request-id":"63b658c1e4d19","uid":"2aecf1"}
```

**Comment by nupplaphil** [comment]
> > ```
> > 2023-01-01T13:50:39+01:00	Friendica[50287]: worker [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (Pa, 01/01/2023, 14:15) at position 0 (P): The timezone could not be found in the database {"worker_id":"d835cc2","worker_cmd":"twitter_sync_run"} - {"file":"DateTimeFormat.php","line":157,"function":"convert","request-id":"63b18184711ef","uid":"801b0c"}
> > 2023-01-01T13:50:39+01:00	Friendica[50287]: worker [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (Pa, 01/01/2023, 14:00) at position 0 (P): The timezone could not be found in the database {"worker_id":"d835cc2","worker_cmd":"twitter_sync_run"} - {"file":"DateTimeFormat.php","line":157,"function":"convert","request-id":"63b18184711ef","uid":"801b0c"}
> > 2023-01-01T13:43:37+01:00	Friendica[110401]: worker [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (Pa, 01/01/2023, 14:15) at position 0 (P): The timezone could not be found in the database {"worker_id":"6bd587f","worker_cmd":"twitter_sync_run"} - {"file":"DateTimeFormat.php","line":157,"function":"convert","request-id":"63b17fde1f680","uid":"78c1e8"}
> > 2023-01-01T13:43:37+01:00	Friendica[110401]: worker [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (Pa, 01/01/2023, 14:00) at position 0 (P): The timezone could not be found in the database {"worker_id":"6bd587f","worker_cmd":"twitter_sync_run"} - {"file":"DateTimeFormat.php","line":157,"function":"convert","request-id":"63b17fde1f680","uid":"78c1e8"}
> > ```
> 
> Please look out for one of these today German time, I'm not sure where the day is supposed to be in the date structure sweat_smile

In german, it's normally DD/MM/YYYY ;-)

Here's a new ones:
```
2023-01-05 03:57:28	Friendica[1131]: index [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (2015-05-22T08:48:00&amp;#43;12:00) at position 19 (&amp;): Unexpected character [] - {"file":"DateTimeFormat.php","line":157,"function":"convert","request-id":"937bd192784370e4bdf066238d90aec0","uid":"bbfc66"}
```
Addressed in https://github.com/friendica/friendica/pull/12641

**Comment by nupplaphil** [comment]
```
2023-01-05T09:07:41+01:00	Friendica[14771]: index [WARNING]: Unable to insert inbox-status row {"url":"https://ieji.de/users/kvakvs/inbox","uri-id":32244698,"created":"2023-01-05 08:07:41","shared":false,"gsid":2741} - {"file":"HTTPSignature.php","line":351,"function":"setInboxStatus","request-id":"ab8c56c19d4863cb78d92614159fb15b","uid":"6755eb"}
```

context:
```
2023-01-05T09:06:47+01:00	{"source": "nginx", "time": 1672906007.990, "resp_body_size": 0, "host": "opensocial.at", "address": "XX.XX.XX.XX", "request_length": 17910, "method": "POST", "uri": "/inbox", "status": 499,  "user_agent": "Friendica 'Giant Rhubarb' 2022.12-1502; https://libranet.de", "resp_time": 41.979, "upstream_addr": "XX.XX.XX.XX:9000", "request_id": "ab8c56c19d4863cb78d92614159fb15b"}
```

**Comment by itmc-rw** [comment]
`2023-01-07T10:06:21Z index [WARNING]: Received null value from preg_replace_callback {"text":"<!DOCTYPE html><html class=\"avada-html-layout-boxed avada-html-header-position-top `

...a massive amount of html follwing until it ends with

`"callstack":"Item::insert, Processor::postItem, Receiver::routeActivities, Receiver::processActivity, Processor::fetchMissingActivity, Processor::fetchParent, Processor::createItem, Receiver::routeActivities, Receiver::processActivity, Processor::fetchMissingActivity"} - {"file":"Strings.php","line":514,"function":"performWithEscapedBlocks","uid":"50f8b0","process_id":817405}`

Addressed in https://github.com/friendica/friendica/pull/12645

**Comment by ghost** [comment]
`index [WARNING]: E_WARNING: foreach() argument must be of type array|object, null given {"code":2,"message":"foreach() argument must be of type array|object, null given","file":"/src/Core/Addon.php","line":316} - {"file":"Addon.php","line":316,"function":"getVisibleList","request-id":"63b9bd7d735e7","uid":"8fe1a5","process_id":2018969}`

Adressed at #12628

**Comment by ghost** [comment]
```
PHP Warning:  Undefined array key "allow_cid" in /src/Model/Item.php on line 824
PHP Warning:  Undefined array key "allow_gid" in /src/Model/Item.php on line 824
PHP Warning:  Undefined array key "deny_cid" in /src/Model/Item.php on line 824
PHP Warning:  Undefined array key "deny_gid" in /src/Model/Item.php on line 824
```
Addressed in https://github.com/friendica/friendica/pull/12643

**Comment by copiis** [comment]
`PHP Warning:  Undefined array key "allow_cid" in /src/Model/Item.php on line 824`

**Comment by ghost** [comment]
`PHP Warning:  sem_acquire(): Failed to acquire key 0x66031b0c: Identifier removed in  /src/Core/Lock/Type/SemaphoreLock.php on line 65`

**Comment by MrPetovan** [comment]
> Here's a new ones:
> 
> ```
> 2023-01-05 03:57:28	Friendica[1131]: index [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (2015-05-22T08:48:00&amp;#43;12:00) at position 19 (&amp;): Unexpected character [] - {"file":"DateTimeFormat.php","line":157,"function":"convert","request-id":"937bd192784370e4bdf066238d90aec0","uid":"bbfc66"}
> ```

Solid double HTML entity encode in a place where it shouldn't be encoded even once.

**Comment by MrPetovan** [comment]
@itmc-rw Can you please post the full message? It should include the `"regex"` key the way you included the `"callstack"` key of the logged message.

**Comment by nupplaphil** [comment]
> > Here's a new ones:
> > 
> > ```
> > 2023-01-05 03:57:28	Friendica[1131]: index [WARNING]: DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (2015-05-22T08:48:00&amp;#43;12:00) at position 19 (&amp;): Unexpected character [] - {"file":"DateTimeFormat.php","line":157,"function":"convert","request-id":"937bd192784370e4bdf066238d90aec0","uid":"bbfc66"}
> > ```
> 
> Solid double HTML entity encode in a place where it shouldn't be encoded even once.

We should really pattern match the format before parsing it into the constructor.. this is not a warning, it's a notice but it pops up because of the unhandled situation *gg*

**Comment by MrPetovan** [comment]
> We should really pattern match the format before parsing it into the constructor.

This is mostly what `DateTimeFormat::fix` is doing. We are doing simple string replacement when we don't need full pattern marching. Note that the `43` in this example would probably be caught by a pattern-matching expression, so it isn't a silver bullet.

**Comment by itmc-rw** [comment]
> @itmc-rw Can you please post the full message? It should include the `"regex"` key the way you included the `"callstack"` key of the logged message.

@MrPetovan  Find it in the attached txt file – too long for a comment.
[warning.txt](https://github.com/friendica/friendica/files/10375558/warning.txt)

**Comment by MrPetovan** [comment]
@itmc-rw Thank you, it was most helpful!

**Comment by ghost** [comment]
`PHP Warning:  Undefined array key "line" in /src/Core/System.php on line 256`

Addressed in https://github.com/friendica/friendica/pull/12645

**Comment by MrPetovan** [comment]
Oh that's mine.

**Comment by Tslmuun** [comment]
Error when changing password
![屏幕截图 2023-01-22 131553](https://user-images.githubusercontent.com/50679343/213901747-9c080b0e-c8c7-42b5-8ac3-9fc1d9c4b11e.png)
Friendica 2023.01
Directory Permissions 755
`FastCGI sent in stderr: "PHP message: PHP Warning:  mkdir(): Permission denied in /var/www/fedi.bar/vendor/divineomega/do-file-cache/src/DOFileCache.php on line 353PHP message: while reading response header from upstream, client: ip, server: fedi.bar, request: "POST /settings/account/password HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.0-fpm.sock:", host: "fedi.bar", referrer: "https://fedi.bar/settings"`

I'm not a programmer, how to fix it？😭
thank you.

**Comment by MrPetovan** [comment]
Hi, this is a file permission issue accessing the temporary directory. Please go in the Admin -> Site -> Advanced and update the "Temporary Path" value to a folder that your web server user can write to.

**Comment by Tslmuun** [comment]
it's working now .
thank you very much!!!!😁

**Comment by ghost** [comment]
`PHP Warning:  Undefined variable $quote in /src/Factory/Api/Mastodon/Status.php on line 261'`

**Comment by ghost** [comment]
`PHP Warning:  sem_acquire(): Failed to acquire key 0x66031b0c: Identifier removed in /src/Core/Lock/Type/SemaphoreLock.php on line 65`

**Comment by ghost** [comment]
`PHP Warning: Trying to access array offset on value of type bool in /src/Factory/Api/Mastodon/Status.php on line 290'`

Addressed in https://github.com/friendica/friendica/pull/12747

**Comment by ghost** [comment]
`PHP Warning: Undefined variable $url in /src/Module/Photo.php on line 354', referer: https://meld.de/profile/rick/contacts`

Addressed in https://github.com/friendica/friendica/pull/12747

**Comment by ghost** [comment]
```
PHP Warning: Undefined variable $http_response_header in /vendor/friendica/json-ld/jsonld.php on line 391
PHP Warning: foreach() argument must be of type array|object, null given in /vendor/friendica/json-ld/jsonld.php on line 391'
```
Addressed in https://git.friendi.ca/friendica/php-json-ld/pulls/1

**Comment by ghost** [comment]
`PHP Warning:  Undefined array key "platform" in /src/Model/GServer.php on line 1420`

Addressed in https://github.com/friendica/friendica/pull/12762

**Comment by DanielSiepmann** [comment]
I guess the version number within the description should contain 2023.01?

I'm running 2023.01 and receive the following issue since today from my cron:
```
PHP Warning:  Trying to access array offset on value of type bool in src/Util/HTTPSignature.php on line 360
PHP Warning:  Trying to access array offset on value of type bool in src/Util/HTTPSignature.php on line 372
PHP Warning:  Trying to access array offset on value of type bool in src/Util/HTTPSignature.php on line 373
PHP Warning:  Trying to access array offset on value of type bool in src/Util/HTTPSignature.php on line 379
```

Not sure what happened as this is just coming up since today.

**Comment by Quix0r** [comment]
`2023-01-29T22:35:00Z index [WARNING]: E_WARNING: Invalid argument supplied for foreach() {"code":2,"message":"Invalid argument supplied for foreach()","file":"/var/www/.../vendor/friendica/json-ld/jsonld.php","line":391} - {"file":"jsonld.php","line":391,"function":"jsonld_default_document_loader","request-id":"63d6f494afadc","uid":"e08ec7","process_id":30812}`
The variable `$http_response_header` isn't declared!

Addressed in https://git.friendi.ca/friendica/php-json-ld/pulls/1

**Comment by MrPetovan** [comment]
It's a "magic" variable set by PHP when an HTTP URL is open in file management functions. However for local files it isn't set.

The warning message is inconsequential, but it has been suppressed in https://git.friendi.ca/friendica/php-json-ld/pulls/1

**Comment by ghost** [comment]
> `2023-01-29T22:35:00Z index [WARNING]: E_WARNING: Invalid argument supplied for foreach() {"code":2,"message":"Invalid argument supplied for foreach()","file":"/var/www/.../vendor/friendica/json-ld/jsonld.php","line":391} - {"file":"jsonld.php","line":391,"function":"jsonld_default_document_loader","request-id":"63d6f494afadc","uid":"e08ec7","process_id":30812}`
> The variable `$http_response_header` isn't declared!

I still get this error message when I try to quote a Twitter post on Friendica.

Addressed at #12832

**Comment by MrPetovan** [comment]
Same answer as for @Quix0r , there is a pull request open to suppress this message and it hasn't been merged yet.

**Comment by AlfredSK** [comment]
`Trying to access array offset on value of type bool in .../src/Factory/Api/Mastodon/Attachment.php on line 117`

2023.03-dev

**Comment by Quix0r** [comment]
> `Trying to access array offset on value of type bool in .../src/Factory/Api/Mastodon/Attachment.php on line 117`

`Photo::selectFirst()` has returned no result and that one wasn't captured/stopped. It could also mean that `$preview_url` now isn't complete.

**Comment by copiis** [comment]
`PHP Warning: Trying to access array offset on value of type bool in /src/Factory/Api/Mastodon/Attachment.php on line 117'`

**Comment by ghost** [comment]
`PHP Warning: Trying to access array offset on value of type bool in /vendor/michelf/php-markdown/Michelf/MarkdownExtra.php on line 525'`

**Comment by Quix0r** [comment]
> vendor/michelf/php-markdown/Michelf/MarkdownExtra.php

The above `preg_split()` command has failed. Can you please try to reproduce it with a higher logging level in your `php.ini` file, check `error_reporting` variable. The documentation says:
````
; Development Value: E_ALL
; Production Value: E_ALL & ~E_DEPRECATED & ~E_STRICT
; http://php.net/error-reporting
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
````

**Comment by ghost** [comment]
> ; Development Value: E_ALL
> ; Production Value: E_ALL & ~E_DEPRECATED & ~E_STRICT
> ; http://php.net/error-reporting
> error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT

Should I enter this in php.ini or how should I raise the loggin lever?

**Comment by nupplaphil** [comment]
```
index [WARNING]: Received null value {"callstack":"Processor::processContent (245), Processor::updateItem (788), Receiver::routeActivities (674), Receiver::processActivity (167)"} - {"file":"Markdown.php","line":115,"function":"toBBCode","request-id":"dcf9a0043edd1a97c9197eccacaeedad","uid":"a83823"}
```
"method": "POST"
"uri": "/inbox"
"status": 202
"user_agent": "PeerTube/5.0.1 (+https://tube.tchncs.de)

Addressed in https://github.com/friendica/friendica/pull/12963

**Comment by ne20002** [comment]
I get this:
```
Uncaught Exception TypeError: "Friendica\Object\Api\Mastodon\Relationship::__construct(): Argument #2 ($contactRecord) must be of type array, bool given, called in /var/www/html/src/Factory/Api/Mastodon/Relationship.php on line 49" at /var/www/html/src/Object/Api/Mastodon/Relationship.php line 80
```
```
TypeError: Friendica\Object\Api\Mastodon\Relationship::__construct(): Argument #2 ($contactRecord) must be of type array, bool given, called in /var/www/html/src/Factory/Api/Mastodon/Relationship.php on line 49 and defined in /var/www/html/src/Object/Api/Mastodon/Relationship.php:80
Stack trace:
#0 /var/www/html/src/Factory/Api/Mastodon/Relationship.php(49): Friendica\Object\Api\Mastodon\Relationship->__construct(76, false, false, false)
#1 /var/www/html/src/Module/Api/Mastodon/Accounts/Relationships.php(57): Friendica\Factory\Api\Mastodon\Relationship->createFromContactId(76, 2)
#2 /var/www/html/src/BaseModule.php(238): Friendica\Module\Api\Mastodon\Accounts\Relationships->rawContent(Array)
#3 /var/www/html/src/Module/BaseApi.php(100): Friendica\BaseModule->run(Array)
#4 /var/www/html/src/App.php(746): Friendica\Module\BaseApi->run(Array)
#5 /var/www/html/index.php(44): Friendica\App->runFrontend(Object(Friendica\App\Router), Object(Friendica\Core\PConfig\Type\JitPConfig), Object(Friendica\Security\Authentication), Object(Friendica\App\Page), Object(Friendica\Util\HTTPInputData), 1677407065.0536)
#6 {main}
```
when trying to unfollow an account who's instance seems to be down

**Comment by nupplaphil** [comment]
```
index [WARNING]: Unable to coerce name from receiver {"receiver":"https://mb.iotib.net"} - {"file":"Processor.php","line":1279,"function":"storeReceivers","request-id":"54c2c13a2084442b77cb276b7f32a823","uid":"af4436"}
```
"method": "POST"
"uri": "/inbox"
"status": 202,
"user_agent": "http.rb/5.1.1 (Mastodon/4.1.0; +https://social.wildeboer.net/)"

Addressed in #12964

**Comment by nupplaphil** [comment]
```
DateTimeFormat::convert: exception: DateTime::__construct(): Failed to parse time string (2023-02-2210T12:00:00.000Z) at position 10 (1): Unexpected character {"worker_id":"568e43b","worker_cmd":"twitter_sync_run"} - {"file":"DateTimeFormat.php","line":157,"function":"convert","request-id":"63fb4e2078a34","uid":"53ad3e"}
```

And another DateTimeFormat :) :)

**Comment by MrPetovan** [comment]
With two different years, it looks familiar to me. A least this time it's actually possible for a human to pick them apart.

**Comment by Quix0r** [comment]
> Should I enter this in php.ini or how should I raise the loggin lever?

Only set `E_ALL` for such scenarios and later please set it back to the recommended productive value.

**Comment by ghost** [comment]
`PHP Warning:  sem_acquire(): Failed to acquire key 0x66031b0c: Identifier removed in /src/Core/Lock/Type/SemaphoreLock.php on line 65`

**Comment by ghost** [comment]
`PHP Warning: Undefined array key "statuses_count" in /src/Protocol/ActivityPub/ClientToServer.php on line 357'`

Addressed in #12963

**Comment by ghost** [comment]
latest dev

```
PHP Warning:  Undefined array key "text" in src/Content/Text/Plaintext.php on line 182
PHP Warning:  Undefined array key "type" in /src/Content/Text/Plaintext.php on line 190
PHP Warning:  Undefined array key "type" in /src/Content/Text/Plaintext.php on line 192
PHP Warning:  Undefined array key "type" in /src/Content/Text/Plaintext.php on line 194
PHP Warning:  Undefined array key "type" in /src/Content/Text/Plaintext.php on line 196
```

**Comment by AlfredSK** [comment]
`Undefined array key "gravity" in .../src/Model/Post/Media.php on line 952`

2023.03-dev, PHP 8.1

**Comment by ghost** [comment]
```
PHP Warning: Attempt to read property "user" on array in /addon/tumblr/tumblr.php on line 222
PHP Warning: Attempt to read property "blogs" on null in /addon/tumblr/tumblr.php on line 222', referer: https://meld.de/settings
```

**Comment by ghost** [comment]
```
PHP Warning: Undefined array key "statuses_count" in /src/Protocol/ActivityPub/ClientToServer.php on line 357'
PHP Warning: Undefined array key "gravity" in /src/Model/Post/Media.php on line 1007', referer: https://meld.de/display/7894ec43-2039a661b92b6a1a-ae61c7c8
```

**Comment by ghost** [comment]
```
PHP Warning: Undefined array key "visibility" in /src/Module/Api/Mastodon/Statuses.php on line 111
PHP Warning: Undefined array key "gravity" in /src/Content/Item.php on line 533
PHP Warning: Undefined array key "verb" in /src/Model/Item.php on line 628', referer: http://[::1]:3036/
```
Addressed in #12963

**Comment by nupplaphil** [comment]
```
Friendica[149791]: index [WARNING]: Application not found {"client_id":"e1f443c5118b2b287627b36578a0f3fb6be8ac0a1cda7cc1c2acd0b808e08ebd","redirect_uri":"https://account.buffer.com/channels/connect?connectingMastodon=true&server=opensocial.at&followBuffer=true"} - {"file":"OAuth.php","line":137,"function":"getApplication","request-id":"04936ff259c6d9cfe88d5f0575c6561e","uid":"cc5800"}
```

Is this a buffer.com issue?

**Comment by MrPetovan** [comment]
@nupplaphil Maybe, you should check the `application` table to see what the redirect URL looks like for the hopefully existing Buffer record.

**Comment by annando** [comment]
@nupplaphil I guess that Buffer is doing things differently with OAuth than the other apps.

**Comment by ghost** [comment]
Warning occurred before git pull now

`PHP Warning:  sem_acquire(): Failed to acquire key 0x66031b0c: Identifier removed in /src/Core/Lock/Type/SemaphoreLock.php on line 65`

**Comment by AlfredSK** [comment]
Current RC, PHP 8.1

`Trying to access array offset on value of type bool in .../src/Factory/Api/Mastodon/Attachment.php on line 140`

Addressed in #12989

**Comment by AlfredSK** [comment]
I guess these are PHP warnings logged to the friendica application log.

```
2023-04-15T08:11:51Z worker [WARNING]: E_WARNING: Undefined array key "id" {"code":2,"message":"Undefined array key \"id\"","file":".../src/Protocol/ActivityPub/Processor.php","line":313} - {"file":"Processor.php","line":313,"function":"createItem","request-id":"643a5c43d250d","uid":"b77813","process_id":2422512}
2023-04-15T08:11:51Z worker [WARNING]: E_WARNING: Undefined array key "id" {"code":2,"message":"Undefined array key \"id\"","file":".../src/Protocol/ActivityPub/Processor.php","line":338} - {"file":"Processor.php","line":338,"function":"createItem","request-id":"643a5c43d250d","uid":"b77813","process_id":2422512}
2023-04-15T08:11:51Z worker [WARNING]: E_WARNING: Undefined array key "id" {"code":2,"message":"Undefined array key \"id\"","file":".../src/Protocol/ActivityPub/Processor.php","line":440} - {"file":"Processor.php","line":440,"function":"createItem","request-id":"643a5c43d250d","uid":"b77813","process_id":2422512}
2023-04-15T08:11:51Z worker [WARNING]: E_WARNING: Undefined array key "sc:identifier" {"code":2,"message":"Undefined array key \"sc:identifier\"","file":".../src/Protocol/ActivityPub/Processor.php","line":448} - {"file":"Processor.php","line":448,"function":"createItem","request-id":"643a5c43d250d","uid":"b77813","process_id":2422512}
```

2023.03-rc, PHP 8.1

**Comment by annando** [comment]
I'm getting masses of these warnings:
```
index [WARNING]: E_WARNING: Undefined array key "pending" {"code":2,"message":"Undefined array key \"pending\"","file":"htdocs/src/Navigation/Notifications/Factory/FormattedNavNotification.php","line":160}
```
