### ISSUE TITLE
[2023.05] Fatal Errors

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#13023]
Please report here any PHP Fatal error message obtained running the 2023.04 stable or 2023.05-dev/rc versions.

Replaces https://github.com/friendica/friendica/issues/12486

**Comment by ghost** [comment]
```
2023-04-24T01:07:09Z index [ERROR]: Uncaught Exception TypeError: "Friendica\Object\Api\Mastodon\InstanceV2\MediaAttachmentsConfig::__construct(): Argument 
#2 ($image_size_limit) must be of type int, string given, called in /src/Module/Api/Mastodon/InstanceV2.php on line 119" at /src/Object/Api/Mastodon/InstanceV2/MediaAttachmentsConfig.php line 41 {"exception":"TypeError: Friendica\\Object\\Api\\Mastodon\\InstanceV2\\MediaAttachmentsConfig::__construct(): Argument 
#2 ($image_size_limit) must be of type int, string given, called in /src/Module/Api/Mastodon/InstanceV2.php on line 119 and defined in /src/Object/Api/Mastodon/InstanceV2/MediaAttachmentsConfig.php:41\nStack trace:\n
#0 /src/Module/Api/Mastodon/InstanceV2.php(119): Friendica\\Object\\Api\\Mastodon\\InstanceV2\\MediaAttachmentsConfig->__construct()\n
#1 /src/Module/Api/Mastodon/InstanceV2.php(86): Friendica\\Module\\Api\\Mastodon\\InstanceV2->buildConfigurationInfo()\n
#2 /src/BaseModule.php(238): Friendica\\Module\\Api\\Mastodon\\InstanceV2->rawContent()\n
#3 /src/Module/BaseApi.php(105): Friendica\\BaseModule->run()\n
#4 /src/App.php(700): Friendica\\Module\\BaseApi->run()\n
#5 /index.php(52): Friendica\\App->runFrontend()\n
#6 {main}"} - {"file":null,"line":null,"function":null,"request-id":"6445d63cf1aee","uid":"1e6093","process_id":1005295}
```
Addressed in https://github.com/friendica/friendica/pull/13048

**Comment by matthiasmoritz** [comment]
ok, still on 2023.03-rc but:
`Unable to retrieve the host in URL: OVERRIDE/.well-known/webfinger?resource=acct%3Aactivitypub%40sandbox.inventaire.io
```
#0 /var/www/friendica/src/Network/HTTPClient/Client/HttpClient.php(206): Friendica\Network\HTTPClient\Client\HttpClient->request()
#1 /var/www/friendica/src/Network/Probe.php(957): Friendica\Network\HTTPClient\Client\HttpClient->get()
#2 /var/www/friendica/src/Network/Probe.php(657): Friendica\Network\Probe::webfinger()
#3 /var/www/friendica/src/Network/Probe.php(618): Friendica\Network\Probe::getWebfinger()
#4 /var/www/friendica/src/Network/Probe.php(730): Friendica\Network\Probe::getWebfingerArray()
#5 /var/www/friendica/src/Network/Probe.php(373): Friendica\Network\Probe::detect()
#6 /var/www/friendica/src/Model/Contact.php(1305): Friendica\Network\Probe::uri()
#7 /var/www/friendica/src/Model/Contact/Relation.php(178): Friendica\Model\Contact::getIdForURL()
#8 /var/www/friendica/src/Model/Contact/Relation.php(136): Friendica\Model\Contact\Relation::updateFollowersFollowings()
#9 /var/www/friendica/src/Worker/ContactDiscovery.php(34): Friendica\Model\Contact\Relation::discoverByUrl()
#10 [internal function]: Friendica\Worker\ContactDiscovery::execute()
#11 /var/www/friendica/src/Core/Worker.php(572): call_user_func_array()
#12 /var/www/friendica/src/Core/Worker.php(386): Friendica\Core\Worker::execFunction()
#13 /var/www/friendica/src/Core/Worker.php(121): Friendica\Core\Worker::execute()
#14 /var/www/friendica/bin/worker.php(83): Friendica\Core\Worker::processQueue()
#15 {main}
```
Adressed in #13100

**Comment by MrPetovan** [comment]
Looks like a badly configured host-meta, here's the content of https://sandbox.inventaire.io/.well-known/host-meta (once you pass through the expired SSL certificate):
```
<?xml version="1.0" encoding="UTF-8"?>
<XRD xmlns="http://docs.oasis-open.org/ns/xri/xrd-1.0">
<Link rel="lrdd" type="application/xrd+xml" template="OVERRIDE/.well-known/webfinger?resource={uri}"/>
</XRD>
```

**Comment by tek-aevl** [comment]
WSOD for my domain. Updated Sunday, everything was fine, then Monday it said it was running the old version, did update again, now no pages load. Moving the tumbler addon does not fix it.

**Comment by MrPetovan** [comment]
You web server/PHP/Friendica logs should have more information about the WSOD.

**Comment by Raroun** [comment]
Im experiencing Out of Memory PHP fatals for some Days. I Don´t knwo why, but the Instance ssem to run normal. I raised the php_max_memory to 3GB, but even with 3GB something runs out of Memory on a daily base.

[26-Apr-2023 10:59:07 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 20480 bytes) in /var/www/html/src/Database/Dat                                                                                                                                                                                    abase.php on line 588
[26-Apr-2023 10:59:09 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 20480 bytes) in /var/www/html/src/Database/DBA                                                                                                                                                                                    .php on line 545
[26-Apr-2023 11:22:26 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 69632 bytes) in /var/www/html/src/Content/Smil                                                                                                                                                                                    ies.php on line 229
[26-Apr-2023 12:08:49 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 20480 bytes) in /var/www/html/src/Model/Post.p                                                                                                                                                                                    hp on line 327
[26-Apr-2023 12:08:51 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 20480 bytes) in /var/www/html/src/Model/Post.p                                                                                                                                                                                    hp on line 327
[26-Apr-2023 12:57:53 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 20480 bytes) in /var/www/html/src/Database/Dat                                                                                                                                                                                    abase.php on line 1655
[26-Apr-2023 12:57:53 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 20480 bytes) in /var/www/html/src/Database/Dat                                                                                                                                                                                    abase.php on line 1655
[26-Apr-2023 13:05:09 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 20480 bytes) in /var/www/html/src/Database/Dat                                                                                                                                                                                    abase.php on line 1655
[26-Apr-2023 13:05:10 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 20480 bytes) in /var/www/html/src/Database/Dat                                                                                                                                                                                    abase.php on line 1655
[26-Apr-2023 14:25:17 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 8192 bytes) in /var/www/html/src/Database/Data                                                                                                                                                                                    base.php on line 975
[26-Apr-2023 15:02:43 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 8192 bytes) in /var/www/html/src/Database/Data                                                                                                                                                                                    base.php on line 975
[26-Apr-2023 15:02:45 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 8192 bytes) in /var/www/html/src/Database/Data                                                                                                                                                                                    base.php on line 975
[26-Apr-2023 15:19:30 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 8192 bytes) in /var/www/html/src/Database/Data                                                                                                                                                                                    base.php on line 1637
[26-Apr-2023 15:19:32 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 8192 bytes) in /var/www/html/src/Database/Data                                                                                                                                                                                    base.php on line 1637
[26-Apr-2023 15:42:59 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 8192 bytes) in /var/www/html/src/Database/Data                                                                                                                                                                                    base.php on line 1637
[26-Apr-2023 15:43:00 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 8192 bytes) in /var/www/html/src/Database/Data                                                                                                                                                                                    base.php on line 1637
[26-Apr-2023 15:50:06 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smil                                                                                                                                                                                    ies.php on line 173
[26-Apr-2023 15:53:09 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 8192 bytes) in /var/www/html/src/Database/Data                                                                                                                                                                                    base.php on line 1637
[26-Apr-2023 15:53:12 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 8192 bytes) in /var/www/html/src/Database/Data                                                                                                                                                                                    base.php on line 1637
[26-Apr-2023 16:28:14 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 8192 bytes) in /var/www/html/src/Database/Data                                                                                                                                                                                    base.php on line 975
[26-Apr-2023 16:28:16 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 8192 bytes) in /var/www/html/src/Database/Data                                                                                                                                                                                    base.php on line 975
[26-Apr-2023 18:12:30 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 8192 bytes) in /var/www/html/src/Database/Data                                                                                                                                                                                    base.php on line 1637
[26-Apr-2023 18:12:32 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 8192 bytes) in /var/www/html/src/Database/Data                                                                                                                                                                                    base.php on line 1637
[27-Apr-2023 14:56:43 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smil                                                                                                                                                                                    ies.php on line 173
[27-Apr-2023 15:20:47 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 20480 bytes) in /var/www/html/src/Database/DBA                                                                                                                                                                                    .php on line 545
[27-Apr-2023 16:21:32 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smil                                                                                                                                                                                    ies.php on line 173
[27-Apr-2023 16:25:01 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smil                                                                                                                                                                                    ies.php on line 173
[27-Apr-2023 19:59:15 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smil                                                                                                                                                                                    ies.php on line 173
[27-Apr-2023 22:22:56 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smil                                                                                                                                                                                    ies.php on line 173
[28-Apr-2023 02:43:47 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smil                                                                                                                                                                                    ies.php on line 173
[28-Apr-2023 05:49:37 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 20480 bytes) in /var/www/html/src/Database/Dat                                                                                                                                                                                    abase.php on line 1637
[28-Apr-2023 06:25:51 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                                                                                    ytes exhausted (tried to allocate 20480 bytes) in /var/www/html/src/Model/Post.p                                                                                                                                                                                    hp on line 327

**Comment by MrPetovan** [comment]
Are there any other errors around these lines? Too bad these don't come with a stack trace, but even then we would need to know the input data.

**Comment by Raroun** [comment]
Nope, no other information in other logs, i am sorry.
Even Friendica log is only mirrorring the php error log.
What i observerd ist that "php-fpm" processes are handling the user requests, while php (without fpm) handles stuff like the worker.
Every now and then a php-fpm process is running, taking much cpu-load, and it runs for like 30 minutes while demanding more and more memory. if it gets to the 3GB limit the process dies. After that, it takes some hours or even a day until this happens again.

**Comment by MrPetovan** [comment]
So, are the Out Of Memory errors coming from php-fpm or php or both?

**Comment by Raroun** [comment]
Only from php-fpm.

**Comment by MrPetovan** [comment]
Please try to set `system.max_recursion_depth` to 20 like this:
```
bin/console config system max_recursion_depth 20
```

**Comment by Raroun** [comment]
did that now - i´ll watch out if that error occurs again

**Comment by ne20002** [comment]
Friendica 2023.04-1
```
TypeError: Friendica\Object\Api\Mastodon\InstanceV2\MediaAttachmentsConfig::__construct(): Argument #2 ($image_size_limit) must be of type int, string given, called in /var/www/html/src/Module/Api/Mastodon/InstanceV2.php on line 119 and defined in /var/www/html/src/Object/Api/Mastodon/InstanceV2/MediaAttachmentsConfig.php:41
Stack trace:
#0 /var/www/html/src/Module/Api/Mastodon/InstanceV2.php(119): Friendica\Object\Api\Mastodon\InstanceV2\MediaAttachmentsConfig->__construct(Array, '256m')
#1 /var/www/html/src/Module/Api/Mastodon/InstanceV2.php(86): Friendica\Module\Api\Mastodon\InstanceV2->buildConfigurationInfo()
#2 /var/www/html/src/BaseModule.php(238): Friendica\Module\Api\Mastodon\InstanceV2->rawContent(Array)
#3 /var/www/html/src/Module/BaseApi.php(105): Friendica\BaseModule->run(Object(Friendica\Module\Special\HTTPException), Array)
#4 /var/www/html/src/App.php(700): Friendica\Module\BaseApi->run(Object(Friendica\Module\Special\HTTPException), Array)
#5 /var/www/html/index.php(52): Friendica\App->runFrontend(Object(Friendica\App\Router), Object(Friendica\Core\PConfig\Type\JitPConfig), Object(Friendica\Security\Authentication), Object(Friendica\App\Page), Object(Friendica\Content\Nav), Object(Friendica\Module\Special\HTTPException), Object(Friendica\Util\HTTPInputData), 1682688495.4309, Array)
#6 {main}
```
Addressed in https://github.com/friendica/friendica/pull/13048

**Comment by MrPetovan** [comment]
How recently did you pull? I intended on fixing this error in https://github.com/friendica/friendica/pull/13048

**Comment by ne20002** [comment]
Updated the docker image this morning (from 2023.04), version shows as 2023.04-1. I stil get this error.

**Comment by MrPetovan** [comment]
Thanks, I don't believe the Docker image is updated with every commit on the `develop` branch so this error will keep showing until you manually apply the patch or upgrade to the next release.

**Comment by ne20002** [comment]
Thank you. I applied the patch manually.

**Comment by Raroun** [comment]
I still get fatals, but it seems that 99% of them are now only in Smilies.php.

[29-Apr-2023 06:34:50 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                     ytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smil                                                                                                                     ies.php on line 173
[29-Apr-2023 07:01:33 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                     ytes exhausted (tried to allocate 69632 bytes) in /var/www/html/src/Content/Smil                                                                                                                     ies.php on line 230
[29-Apr-2023 09:44:42 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                     ytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smil                                                                                                                     ies.php on line 173
[29-Apr-2023 09:51:07 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                     ytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smil                                                                                                                     ies.php on line 173
[29-Apr-2023 10:04:59 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                     ytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smil                                                                                                                     ies.php on line 173
[29-Apr-2023 10:05:18 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                     ytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smil                                                                                                                     ies.php on line 173
[29-Apr-2023 11:58:55 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                     ytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smil                                                                                                                     ies.php on line 173
[29-Apr-2023 14:12:24 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                     ytes exhausted (tried to allocate 20480 bytes) in /var/www/html/src/Database/Dat                                                                                                                     abase.php on line 975
[29-Apr-2023 14:21:25 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                     ytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smil                                                                                                                     ies.php on line 173
[29-Apr-2023 15:41:00 UTC] PHP Notice:  iconv(): Detected an illegal character i                                                                                                                     n input string in /var/www/html/src/Util/ParseUrl.php on line 308
[29-Apr-2023 15:47:43 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                     ytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smil                                                                                                                     ies.php on line 173
[29-Apr-2023 16:22:34 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                     ytes exhausted (tried to allocate 8192 bytes) in /var/www/html/src/Database/Data                                                                                                                     base.php on line 1637
[29-Apr-2023 17:22:29 UTC] PHP Notice:  iconv(): Detected an illegal character i                                                                                                                     n input string in /var/www/html/src/Util/ParseUrl.php on line 308
[29-Apr-2023 20:08:48 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                     ytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smil                                                                                                                     ies.php on line 173
[29-Apr-2023 21:00:14 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                     ytes exhausted (tried to allocate 69632 bytes) in /var/www/html/src/Content/Smil                                                                                                                     ies.php on line 230
[29-Apr-2023 21:57:47 UTC] PHP Fatal error:  Allowed memory size of 3221225472 b                                                                                                                     ytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smil                                                                                                                     ies.php on line 173

**Comment by matthiasmoritz** [comment]
Have the same issue here as @Raroun

**Comment by MrPetovan** [comment]
Without the full trace or some context, it's hard to troubleshoot. Do you experience any white screen of death (abbreviated WSOD in these parts)?

**Comment by Raroun** [comment]
@MrPetovan 
There is no WSOD.
I even tried to set the max_memory per process to 6 gigabyte and this still happens.
Every now and then a fpm process starts and eats up all memory till it gets killed because of memory consumption.

I looked at the code and there is a recursive replacement function for Smilies in SMilies.php Line 173.
I think there are somewhere big posts or at least big data chunks that gets processed and never finish.
I know it´s not really helpfull :(

**Comment by Raroun** [comment]
i had a look at the logs again, i don´t know if it is helpfull, but at least one dying process starts nearly at the exact time of the day. it could be a hint. also i noticed the html purifier :)


[01-May-2023 11:55:12 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[01-May-2023 12:38:31 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173

**[01-May-2023 15:53:29 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173**

[02-May-2023 01:06:48 UTC] PHP Notice:  iconv(): Detected an illegal character in input string in /var/www/html/src/Util/ParseUrl.php on line 308

**[02-May-2023 15:55:18 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173**

[02-May-2023 19:27:54 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 8192 bytes) in /var/www/html/src/Database/Database.php on line 975
[03-May-2023 08:27:09 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[03-May-2023 08:38:05 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[03-May-2023 15:06:22 UTC] PHP Warning:  gethostbyname(): Host name cannot be longer than 255 characters in /var/www/html/src/Network/HTTPClient/Client/HttpClient.php on line 76

**[03-May-2023 15:54:28 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173**

[03-May-2023 17:40:26 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/src/Database/Database.php on line 599
[04-May-2023 10:01:04 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 24576 bytes) in /var/www/html/src/Database/Database.php on line 975
[04-May-2023 10:01:24 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 24576 bytes) in /var/www/html/src/Database/Database.php on line 975
[04-May-2023 10:54:27 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[04-May-2023 15:39:31 UTC] PHP Notice:  iconv(): Detected an illegal character in input string in /var/www/html/src/Util/ParseUrl.php on line 308

**_[04-May-2023 15:56:23 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 262144 bytes) in /var/www/html/vendor/ezyang/htmlpurifier/library/HTMLPurifier/PropertyList.php on line 41_**

[04-May-2023 19:49:52 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/src/Database/Database.php on line 599
[04-May-2023 19:49:59 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/src/Database/Database.php on line 599
[04-May-2023 19:50:29 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/src/Database/Database.php on line 599
[04-May-2023 19:52:08 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/src/Database/Database.php on line 599
[04-May-2023 20:29:45 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[05-May-2023 15:55:23 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[06-May-2023 14:38:22 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/src/Database/Database.php on line 599
[06-May-2023 15:19:28 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 8192 bytes) in /var/www/html/src/Database/Database.php on line 975
[06-May-2023 15:20:54 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 8192 bytes) in /var/www/html/src/Database/Database.php on line 975

**[06-May-2023 15:54:25 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 262144 bytes) in /var/www/html/src/Database/DBA.php on line 543**
**[06-May-2023 15:54:26 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 16384 bytes) in /var/www/html/src/Database/Database.php on line 599**
**[06-May-2023 15:54:51 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173**

**[07-May-2023 15:53:50 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173**

[08-May-2023 05:41:19 UTC] PHP Warning:  iconv(): Wrong encoding, conversion from &quot;none&quot; to &quot;UTF-8//TRANSLIT&quot; is not allowed in /var/www/html/src/Util/ParseUrl.php on line 308
[08-May-2023 08:05:03 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[08-May-2023 08:06:54 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[08-May-2023 08:08:34 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[08-May-2023 08:09:34 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[08-May-2023 09:26:15 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[08-May-2023 09:28:27 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[08-May-2023 09:31:25 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173

**[08-May-2023 15:53:51 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173**

[08-May-2023 18:29:40 UTC] PHP Warning:  Undefined array key "type" in /var/www/html/src/Protocol/ActivityPub/Processor.php on line 1145

**[09-May-2023 15:55:04 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173**

**Comment by MrPetovan** [comment]
So, if it is a php-fpm process, then it isn't a worker task. It probably is an incoming message that would hit a public endpoint, which explains the absence of WSOD. And since the text processing fails, I guess no record exists, and since the request failed, the remote system retries at regular intervals.

It narrows down the scope, but it still isn't enough to catch the culprit. I wonder if we can catch the OOM fatal errors in PHP. I'm guessing we can't, so we could implement a memory checker that issues a log message when the used memory is reaching 80-90% of the limit.

**Comment by Raroun** [comment]
at least this sound like a plan :)
i keep observing the logs :)

**Comment by annando** [comment]
@Raroun these errors mostly occur when the system tries to load a thread with to many entries. You can reduce the number of maximum posts per thread. This most likely solves the issue.

**Comment by MrPetovan** [comment]
If it was the case, then WSOD would occur, which they apparently don't. Also the timing of these errors suggests an automated retrying rather than human users trying to open a long thread in the Web UI.

**Comment by Raroun** [comment]
Since some of my users try to embedd like Videos or Soundfiles, im experiencing many uncaught Exceptions lately.

Like this one:


`2023-05-14T18:57:48Z | ERROR | index | Uncaught Exception InvalidArgumentException: "Unable to retrieve the host in URL: [/embed]]https://soundcloud.com/user-902628730-730396397/it-flows-somehow?si=8ab2471f89794bb39e4555d2dd4bace4&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing" at /var/www/html/src/Network/HTTPClient/Client/HttpClient.php line 73
`

Stacktrace:

```
InvalidArgumentException: Unable to retrieve the host in URL: [/embed]]https://soundcloud.com/user-902628730-730396397/it-flows-somehow?si=8ab2471f89794bb39e4555d2dd4bace4&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing in /var/www/html/src/Network/HTTPClient/Client/HttpClient.php:73


#0 /var/www/html/src/Network/HTTPClient/Client/HttpClient.php(206): Friendica\Network\HTTPClient\Client\HttpClient->request()
#1 /var/www/html/src/Network/HTTPClient/Client/HttpClient.php(287): Friendica\Network\HTTPClient\Client\HttpClient->get()
#2 /var/www/html/src/Network/HTTPClient/Client/HttpClient.php(272): Friendica\Network\HTTPClient\Client\HttpClient->fetchFull()
#3 /var/www/html/src/Content/OEmbed.php(107): Friendica\Network\HTTPClient\Client\HttpClient->fetch()
#4 /var/www/html/src/Content/OEmbed.php(61): Friendica\Content\OEmbed::fetchURL()
#5 [internal function]: Friendica\Content\OEmbed::replaceCallback()
#6 /var/www/html/src/Content/OEmbed.php(319): preg_replace_callback()
#7 /var/www/html/src/Content/Text/BBCode.php(1685): Friendica\Content\OEmbed::BBCode2HTML()
#8 /var/www/html/src/Util/Strings.php(517): Friendica\Content\Text\BBCode::Friendica\Content\Text\{closure}()
#9 /var/www/html/src/Content/Text/BBCode.php(2224): Friendica\Util\Strings::performWithEscapedBlocks()
#10 /var/www/html/src/Content/Text/BBCode.php(1902): Friendica\Content\Text\BBCode::performWithEscapedTags()
#11 /var/www/html/src/Util/Strings.php(517): Friendica\Content\Text\BBCode::Friendica\Content\Text\{closure}()
#12 /var/www/html/src/Content/Text/BBCode.php(2224): Friendica\Util\Strings::performWithEscapedBlocks()
#13 /var/www/html/src/Content/Text/BBCode.php(1915): Friendica\Content\Text\BBCode::performWithEscapedTags()
#14 /var/www/html/src/Content/Text/BBCode.php(237): Friendica\Content\Text\BBCode::convert()
#15 /var/www/html/src/Model/Item.php(1967): Friendica\Content\Text\BBCode::toPlaintext()
#16 /var/www/html/src/Model/Item.php(1940): Friendica\Model\Item::getLanguageArray()
#17 /var/www/html/src/Model/Item.php(1174): Friendica\Model\Item::getLanguage()
#18 /var/www/html/mod/item.php(200): Friendica\Model\Item::insert()
#19 /var/www/html/mod/item.php(79): item_insert()
#20 /var/www/html/src/LegacyModule.php(96): item_post()
#21 /var/www/html/src/LegacyModule.php(80): Friendica\LegacyModule->runModuleFunction()
#22 /var/www/html/src/BaseModule.php(228): Friendica\LegacyModule->post()
#23 /var/www/html/src/App.php(700): Friendica\BaseModule->run()
#24 /var/www/html/index.php(52): Friendica\App->runFrontend()
#25 {main}

```

**Comment by Raroun** [comment]
Or this one:

`2023-05-16T08:36:56Z | ERROR | index | Uncaught Exception InvalidArgumentException: "Unable to retrieve the host in URL: [url]https://friendica.opensocial.space/display/4c906314-2164-5dd0-5f47-956670286269" at /var/www/html/src/Network/HTTPClient/Client/HttpClient.php line 73`

Stacktrace:

```
InvalidArgumentException: Unable to retrieve the host in URL:  [url]https://friendica.opensocial.space/display/4c906314-2164-5dd0-5f47-956670286269 in /var/www/html/src/Network/HTTPClient/Client/HttpClient.php:73
Stack trace:
#0 /var/www/html/src/Network/HTTPClient/Client/HttpClient.php(206): Friendica\Network\HTTPClient\Client\HttpClient->request()
#1 /var/www/html/src/Network/HTTPClient/Client/HttpClient.php(287): Friendica\Network\HTTPClient\Client\HttpClient->get()
#2 /var/www/html/src/Network/HTTPClient/Client/HttpClient.php(272): Friendica\Network\HTTPClient\Client\HttpClient->fetchFull()
#3 /var/www/html/src/Content/OEmbed.php(107): Friendica\Network\HTTPClient\Client\HttpClient->fetch()
#4 /var/www/html/src/Content/OEmbed.php(61): Friendica\Content\OEmbed::fetchURL()
#5 [internal function]: Friendica\Content\OEmbed::replaceCallback()
#6 /var/www/html/src/Content/OEmbed.php(319): preg_replace_callback()
#7 /var/www/html/src/Content/Text/BBCode.php(1685): Friendica\Content\OEmbed::BBCode2HTML()
#8 /var/www/html/src/Util/Strings.php(517): Friendica\Content\Text\BBCode::Friendica\Content\Text\{closure}()
#9 /var/www/html/src/Content/Text/BBCode.php(2224): Friendica\Util\Strings::performWithEscapedBlocks()
#10 /var/www/html/src/Content/Text/BBCode.php(1902): Friendica\Content\Text\BBCode::performWithEscapedTags()
#11 /var/www/html/src/Util/Strings.php(517): Friendica\Content\Text\BBCode::Friendica\Content\Text\{closure}()
#12 /var/www/html/src/Content/Text/BBCode.php(2224): Friendica\Util\Strings::performWithEscapedBlocks()
#13 /var/www/html/src/Content/Text/BBCode.php(1915): Friendica\Content\Text\BBCode::performWithEscapedTags()
#14 /var/www/html/src/Content/Text/BBCode.php(1206): Friendica\Content\Text\BBCode::convert()
#15 /var/www/html/mod/message.php(309): Friendica\Content\Text\BBCode::convertForUriId()
#16 /var/www/html/src/LegacyModule.php(96): message_content()
#17 /var/www/html/src/LegacyModule.php(73): Friendica\LegacyModule->runModuleFunction()
#18 /var/www/html/src/BaseModule.php(244): Friendica\LegacyModule->content()
#19 /var/www/html/src/App.php(700): Friendica\BaseModule->run()
#20 /var/www/html/index.php(52): Friendica\App->runFrontend()
#21 {main}
```
I don´t know what the [URL] is doing in the logs, but it is probably a hint.

This error is related to my post above this post:

[Click here to see the post](https://art1sec.uber.space/display/f511c56c-1164-633a-e4c4-875883698721)

**Comment by Raroun** [comment]
Note: After this Errors occured, i changed the instance to 2023.06 develop.

**Comment by MrPetovan** [comment]
It would be helpful to have the original BBCode text that triggered the error. Did you add two `[embed]` tags in the same post? For the second error, did you add a `[ur]` tag inside a `[embed]` tag?

**Comment by Raroun** [comment]
This is the Plain text of the URL post:

```
@zwovierzwo@social.fedinet.de 

Derzeit geht es nur über Umwege und nicht wirklich zufriedenstellend.
Ist ein heiss ersehntes Feature - es gab vor kurzem auch einen Beitrag dazu -> [url=https://rytter.me/display/4c906314-2164-5dd0-5f47-956670286269]hier[/url].
```
Seems right for me.
there is no `[embed]` :)
For the Error of the "embedd one" - i asked the user. - waiting for a reply.
 He tried to embedd an audio streams which didn´t work.

**Comment by MrPetovan** [comment]
Thank you, "Plaintext" has a specific meaning, do you mean the BBCode source of the post?

**Comment by Raroun** [comment]
I worte it excatly into the windows as it is in the code block above :)
So i guess its the bbCode source :)

**Comment by MrPetovan** [comment]
It's perfect, thank you!

**Comment by Raroun** [comment]
This bbcode:
`[embed]https://soundcloud.com/user-902628730-730396397/bluesing?si=95afa36ec2e04616bde427c308c4e32b&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing[/embed]`

leads to his:

`2023-05-16T14:58:01Z | ERROR | index | Uncaught Exception InvalidArgumentException: "Unable to retrieve the host in URL: «block-6724723387184053235-0»</p><p><br>[embed]https://soundcloud.com/user-902628730-730396397/bluesing?si=95afa36ec2e04616bde427c308c4e32b&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing" at /var/www/html/src/Network/HTTPClient/Client/HttpClient.php line 73
`

Stacktrace:

```
InvalidArgumentException: Unable to retrieve the host in URL: «block-6724723387184053235-0»</p><p><br>[embed]https://soundcloud.com/user-902628730-730396397/bluesing?si=95afa36ec2e04616bde427c308c4e32b&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing in /var/www/html/src/Network/HTTPClient/Client/HttpClient.php:73
Stack trace:
#0 /var/www/html/src/Network/HTTPClient/Client/HttpClient.php(206): Friendica\Network\HTTPClient\Client\HttpClient->request()
#1 /var/www/html/src/Network/HTTPClient/Client/HttpClient.php(287): Friendica\Network\HTTPClient\Client\HttpClient->get()
#2 /var/www/html/src/Network/HTTPClient/Client/HttpClient.php(272): Friendica\Network\HTTPClient\Client\HttpClient->fetchFull()
#3 /var/www/html/src/Content/OEmbed.php(107): Friendica\Network\HTTPClient\Client\HttpClient->fetch()
#4 /var/www/html/src/Content/OEmbed.php(61): Friendica\Content\OEmbed::fetchURL()
#5 [internal function]: Friendica\Content\OEmbed::replaceCallback()
#6 /var/www/html/src/Content/OEmbed.php(319): preg_replace_callback()
#7 /var/www/html/src/Content/Text/BBCode.php(1685): Friendica\Content\OEmbed::BBCode2HTML()
#8 /var/www/html/src/Util/Strings.php(517): Friendica\Content\Text\BBCode::Friendica\Content\Text\{closure}()
#9 /var/www/html/src/Content/Text/BBCode.php(2224): Friendica\Util\Strings::performWithEscapedBlocks()
#10 /var/www/html/src/Content/Text/BBCode.php(1902): Friendica\Content\Text\BBCode::performWithEscapedTags()
#11 /var/www/html/src/Util/Strings.php(517): Friendica\Content\Text\BBCode::Friendica\Content\Text\{closure}()
#12 /var/www/html/src/Content/Text/BBCode.php(2224): Friendica\Util\Strings::performWithEscapedBlocks()
#13 /var/www/html/src/Content/Text/BBCode.php(1915): Friendica\Content\Text\BBCode::performWithEscapedTags()
#14 /var/www/html/src/Content/Text/BBCode.php(237): Friendica\Content\Text\BBCode::convert()
#15 /var/www/html/src/Model/Item.php(1967): Friendica\Content\Text\BBCode::toPlaintext()
#16 /var/www/html/src/Model/Item.php(1940): Friendica\Model\Item::getLanguageArray()
#17 /var/www/html/src/Model/Item.php(1174): Friendica\Model\Item::getLanguage()
#18 /var/www/html/mod/item.php(200): Friendica\Model\Item::insert()
#19 /var/www/html/mod/item.php(79): item_insert()
#20 /var/www/html/src/LegacyModule.php(96): item_post()
#21 /var/www/html/src/LegacyModule.php(80): Friendica\LegacyModule->runModuleFunction()
#22 /var/www/html/src/BaseModule.php(228): Friendica\LegacyModule->post()
#23 /var/www/html/src/App.php(703): Friendica\BaseModule->run()
#24 /var/www/html/index.php(52): Friendica\App->runFrontend()
#25 {main}
```

**Comment by Raroun** [comment]
![fatal](https://github.com/friendica/friendica/assets/10846157/537a81d0-ac24-4e8a-a418-17e7abd19962)

**Comment by Raroun** [comment]
This seems to work in 2023.06 dev:

`[audio]https://soundcloud.com/user-902628730-730396397/bluesing?si=95afa36ec2e04616bde427c308c4e32b&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing[/audio]
`

Thanks to fynhv@friendica.opensocial.space for the tests :)

**Comment by FynhF** [comment]
No problem, thanks for posting it here. :D

> This seems to work in 2023.06 dev:

Well, it sort of works as in it breaks nothing. 
But according to the user documentation `[audio][/audio]` should be used for referring to an audio **file**, which should then be embed as a HTML5 player.

From the Friendica user documentation at https://wiki.friendi.ca/docs/bbcode:

> [audio]Audio file url[/audio]</td>
>`<td>Full URL to an ogg/ogv/oga/ogm/webm/mp4/mp3 file. An HTML5 player will be used to show it.</td>`

**Comment by FynhF** [comment]
No problem, thanks for posting it here. :D

> This seems to work in 2023.06 dev:

Well, it sort of works as in it doesn't lead to an error. 
But according to the user documentation `[audio][/audio]` should actually be used for referring to an audio **file**, which should then be embed as a HTML5 player. Which doesn't seem to work properly.

From the Friendica user documentation at https://wiki.friendi.ca/docs/bbcode:

> [audio]Audio file url[/audio]</td>
>`<td>Full URL to an ogg/ogv/oga/ogm/webm/mp4/mp3 file. An HTML5 player will be used to show it.</td>`


But this is most likely doesn't belong here, should I open an issue for that?

**Comment by FynhF** [comment]
Addition: 

`[audio][/audio]` seems to work as intended when you use it with a deep link to a any of the given file types. 

I just tried it with the download link of a shared mp3-file in my Nextcloud that ends in .mp3. It was embedded as intended in form of a HTML5 audio player.

As the soundcloud link in Rarouns example doesn't link to a file, it's probably the expected outcome that it's not embedded as a player when using `[audio][/audio]`.

**Comment by nuciluc** [comment]
> So, are the Out Of Memory errors coming from php-fpm or php or both?

on our system the error come from the worker.
default php cli had no limit, so then we started setting 512M and we moved to 640M.
we tried also to change max_recursion_depth, but the errors are still there.

it is not a big issue, but right now we are not able to understand why this is happening

**Comment by Raroun** [comment]
It is probably a bit early to say, but after fetching this
[Pull Request 13140](https://github.com/friendica/friendica/pull/13140)
There where no more out of memory issues today since 10 am. There were about 40 OOM´s in the php log everyday.

**Comment by Raroun** [comment]
[20-May-2023 00:14:54 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[20-May-2023 00:34:58 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[20-May-2023 00:54:07 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[20-May-2023 01:14:29 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[20-May-2023 01:34:32 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[20-May-2023 01:54:42 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[20-May-2023 02:14:39 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[20-May-2023 02:35:06 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[20-May-2023 02:55:00 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[20-May-2023 03:14:24 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[20-May-2023 03:34:12 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[20-May-2023 03:54:35 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[20-May-2023 04:14:21 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[20-May-2023 04:34:12 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[20-May-2023 04:44:54 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/src/Database/DBA.php on line 545
[20-May-2023 04:54:48 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[20-May-2023 05:14:43 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[20-May-2023 05:34:44 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[20-May-2023 05:35:17 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 8192 bytes) in /var/www/html/src/Database/Database.php on line 1643
[20-May-2023 05:51:25 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 8192 bytes) in /var/www/html/src/Database/Database.php on line 1643
[20-May-2023 05:51:54 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 8192 bytes) in /var/www/html/src/Database/Database.php on line 1643
[20-May-2023 05:52:14 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 8192 bytes) in /var/www/html/src/Database/Database.php on line 1643
[20-May-2023 05:54:38 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[20-May-2023 06:14:21 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[20-May-2023 06:34:41 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[20-May-2023 06:54:31 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[20-May-2023 07:14:26 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[20-May-2023 07:34:58 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[20-May-2023 07:54:53 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[20-May-2023 08:14:24 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[20-May-2023 08:34:46 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[20-May-2023 08:54:21 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[20-May-2023 09:03:27 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[20-May-2023 09:15:05 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[20-May-2023 09:34:18 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
[20-May-2023 09:55:01 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173
**[20-May-2023 10:14:37 UTC] PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 81920 bytes) in /var/www/html/src/Content/Smilies.php on line 173**

Thats the last entry right before the pull.

**Comment by Raroun** [comment]
Nope, i is not too  early to say.
Since 8 hours not a single OOM Exception.
Thanks to @annando for fixing this and thanks to @MrPetovan for bearing with me :)

**Comment by MrPetovan** [comment]
Self-fixing issues are the best issues.
