### ISSUE TITLE
missing content() calls in POST requests

### ISSUE THREAD

**Issue by bmillwood** [friendica/friendica#14469]
- [X] I have searched open and closed issues for duplicates

### Bug Description

- #14326 stopped `content()` (as well as `rawContent()`) from being called for POST requests. But many pages with `post()` handlers expect to output some content on the resulting page, e.g. the 2FA app-specific passwords pages (indeed, this is the *only* way to see your app-specific passwords), and I suspect #14450 is the same thing as well. (Edit: both of those issues have now been worked around by redirecting the relevant POST page to a GET page instead.)

- I note that the description of `post()` in the `BaseModule` class says ["Doesn't display any content"](https://github.com/friendica/friendica/blob/434aa1b1743ce5d6412e5534cb4003c551a140ba/src/BaseModule.php#L144) which makes me lean in the direction of reverting #14326 and instead fixing #14325 by removing the `addJsonContent` in `PushSubscription::post()`, but you could also go the other way and just replace `addJsonContent` with `jsonExit` or something (and possibly revise the comment on `post()`).

### Steps to Reproduce

Edit: As of 2024.12 this specific manifestation of the issue has been worked around. I think this issue still identifies something about the code that could be better, but I'm now not aware of any broken functionality caused by it. See comments for more discussion.

1. ~Create an app-specific password~

#### Actual Result:

~The page that's supposed to show you the generated password is blank instead. The password has been generated, but you can't see it.~

#### Expected Result:

~You see the page with your generated password on it.~

### Screenshots

~The page before I click generate:~
![2024-10-16-181126_2230x1197_scrot](https://github.com/user-attachments/assets/d4213904-a604-4269-8129-ebc5ad8eeaa2)
~The blank page I see when I click generate:~
![2024-10-16-181137_2231x929_scrot](https://github.com/user-attachments/assets/c4442843-f9b4-450f-9b4f-ecfb0e2594d7)
~When I go back in the browser, I see the generation succeeded:~
![2024-10-16-181148_1269x550_scrot](https://github.com/user-attachments/assets/34afd9e8-5050-4bcf-b8ba-7d2b4e7c8a48)

### Platform Info

Friendica Version: 2024.08

Friendica Source: https://github.com/bmillwood/nixos-friendica (which goes via GitHub)

PHP version: 8.2.24

SQL version: mysql  Ver 15.1 Distrib 10.11.8-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by bmillwood** [comment]
- nb. #14450 was fixed by simply modifying the installation procedure to use GET instead of POST, working around this issue

**Comment by MrPetovan** [comment]
I've tried to reproduce this issue but I'm being shown content after clicking on "Generate". See following screenshot:
![image](https://github.com/user-attachments/assets/7fd32f7e-e9b6-4838-944e-8561929ece48)
Can you confirm you still get a blank page after creating an app-specific password?

**Comment by bmillwood** [comment]
You're right, I can't reproduce this issue in 2024.12. Looks like dc4eac2742c09199e0a8a6a85c0129a7097e4a9d fixed it, but again, it feels like a workaround to me: it redirects back to a GET request and puts your app-specific password in a notification tooltip. Notice, for example, that [this message](https://github.com/friendica/friendica/blob/86c3fdbd2b12b6fac370c740d9ac2b4614009961/src/Module/Settings/TwoFactor/AppSpecific.php#L121) isn't ever shown anymore, because `$this->appSpecificPassword` is supposed to be set by `post()` and then used by `content()`, but now we never reach `content()` if we called `post()`.

**Comment by MrPetovan** [comment]
I hear you, and I believe we can do better.

**Comment by bmillwood** [comment]
> I hear you, and I believe we can do better.

Thanks :) In the meantime I updated the original issue description to reflect the workarounds.
