### ISSUE TITLE
Fix [Embedded content - reload the page to view]

### ISSUE THREAD

**Issue by Hypolite** [friendica/friendica#2822]
I know there was issue #1290 opened about it but I cannot reopen it. Apparently nobody currently remembers why we remove media tags when the network stream is reloaded via Ajax. I want to take a stab at either fixing the original issue, or find out exactly why it was set like this in the first place.

**Comment by zotlabs** [comment]
There were two issues. First was browser prefetch. If it's a media file some browsers will try and load the entire thing before the javascript update finishes. This means the javascript update will often not finish for a few minutes and the browser is completely unresponsive during this time, since JS is single-threaded.  I believe this was due to early html5 browser implementations and doesn't seem to be a problem any more. But the other thing we had to do is to prevent all conversation updates whilst a media element is playing in order to prevent the attached media from starting over if likes started coming in for the video you're currently watching. This is for html5 audio/video. For oembeds, you probably want to blacklist scribd, since it will gladly send the browser an entire 50M ebook every time the conversation reloads. This is a variation of the prefetch issue. Strictly speaking it isn't browser prefetch, but it's quite nasty to deal with when using ajax updates - and in some countries like my own they don't really sell internet service, they sell bandwidth.

**Comment by Hypolite** [comment]
What about creating a user setting called something like "Bandwidth saver"? It would makes sense to me to remove the blanket embed ban on Ajax reload since the technical issue seems to have been solved in modern browsers.

**Comment by zotlabs** [comment]
You still have to fix the video restart. That is an application issue. And the oembed bandwidth problem will be solved by fixing friendica oembed security, which really needs fixing anyway.  You could remove the restriction before fixing these things but they'll come back to bite. We've been running for a few years now without media restrictions on ajax, but it took some work to get there.

**Comment by Hypolite** [comment]
> You still have to fix the video restart.

Not sure what you are talking about. Even in the current paradigm with the embed replacement, the video/audio is cut when the content is updated from Ajax. The "Bandwidth Saver" settings would not change anything about the media being abruptly cut on update. It could be a separate issue but at least medias would show when they are first added to the stream via Ajax.

What is exactly the issue with oembed security? Local execution of a malicious embed?

**Comment by zotlabs** [comment]
You missed the restart solution. We query all the media elements on the page and if any are playing or paused we delay ajax updates until it's finished.

You won't have to dig very deep to discover the oembed issues.
