### ISSUE TITLE
Frio: Feature requests for the new composer page

### ISSUE THREAD

**Issue by annando** [friendica/friendica#7671]
The new composer page is looking promising, but currently it does have some issues that prevents me from using it. It would be nice if these can be handled:
* You currently don't seem to be able to control the connector settings, so you cannot select or deselect some connectors from that specific post.
* The virtual group "followers" does include mail addresses as well. It would be nice having some control about this as well. I - personally - would like to exclude these from the "followers".
* I do have some test group called "ich". For some reason this isn't available in the search.
* It would be great, having a possibility to browse through the groups and users without the need to type the first letter. Possibly through some lookup button?
* Possibly the deselected option (public or private) could be greyed out a little bit to better visualize which is the current option? I must confess that I was a little bit unsure if just inflating and deflating the option pane really is enough - or if one has to do some other magic to activate it.

**Comment by MrPetovan** [comment]
> You currently don't seem to be able to control the connector settings, so you cannot select or deselect some connectors from that specific post.

I can see the checkbox for the Twitter connector, doesn't it work?

**Comment by AlfredSK** [comment]
Yep. I'm using the compose page. I can select and deselect the connectors (Twitter, Tumblr). And it works.

**Comment by annando** [comment]
Where do I do it?
![Bildschirmfoto 2019-09-28 um 17 21 43](https://user-images.githubusercontent.com/844208/65818716-8def3c00-e214-11e9-882e-2eb3834a2a1c.png)

**Comment by AlfredSK** [comment]
Here... :-)

![image](https://user-images.githubusercontent.com/3656054/65818861-086c8b80-e216-11e9-8270-0d07964c1669.png)

**Comment by MrPetovan** [comment]
It should be in the Öffentlich tab.
![friendica-compose-connector](https://user-images.githubusercontent.com/925415/65818867-cb87a100-e1e3-11e9-91c0-203c181cbdb4.png)

**Comment by AlfredSK** [comment]
I remember I had some caching issues after I enabled the composer page for the first time.

**Comment by MrPetovan** [comment]
> * The virtual group "followers" does include mail addresses as well. It would be nice having some control about this as well. I - personally - would like to exclude these from the "followers".

Is there a specific rationale about this? Are mail contacts not delivered posts by default?

> * It would be great, having a possibility to browse through the groups and users without the need to type the first letter. Possibly through some lookup button?

This is tricky, do you know how Facebook handles this?

> * Possibly the deselected option (public or private) could be greyed out a little bit to better visualize which is the current option? I must confess that I was a little bit unsure if just inflating and deflating the option pane really is enough - or if one has to do some other magic to activate it.

It is doable. There is a toggling CSS class to denote opened or closed.

**Comment by MrPetovan** [comment]
Not luck reproducing the `Ich` named user group issue.

![friendica-compose-group-ich](https://user-images.githubusercontent.com/925415/66708510-522d9980-ed1f-11e9-9055-4cf3b2370628.png)

**Comment by MrPetovan** [comment]
How does this look?
![friendica-compose-private-greyed-out](https://user-images.githubusercontent.com/925415/66708649-c0735b80-ed21-11e9-82b6-933be189edd3.png)
![friendica-compose-public-greyed-out](https://user-images.githubusercontent.com/925415/66708650-c0735b80-ed21-11e9-972d-94ea936ed217.png)

**Comment by annando** [comment]
AFAIK mail contacts are only addressed when explicitly added in a group. On public posts - for example - they aren't. Concerning the "ich" problem: Are groups always shown as first entry? Because I had several contacts shown up who contained "ich" in the same - but not the group.

Concerning your greyed out example: That's fine!

**Comment by tobiasd** [comment]
In the ACL dialog, there is a check-box to send the posting to email contacts as well. Don't know how it is in frio.

**Comment by MrPetovan** [comment]
It should appear if it was appearing in the modal ACL tab. It wasn't appearing for me before the Compose page but I don't have any email contact either.

**Comment by annando** [comment]
From my point of view, most of the mentioned points are fulfilled. I would close this issue, if no one disagrees.

**Comment by MrPetovan** [comment]
What is remaining except Tobias' mysterious "DE" group disappearance?

**Comment by annando** [comment]
I can imagine that the source of his problem was the same like mine. It would be greatif he could check and confirm it.

**Comment by MrPetovan** [comment]
He sent me his JSON data that is injected in the ACL Javascript.

**Comment by annando** [comment]
So it isn't my problem?

**Comment by MrPetovan** [comment]
Yesterday I was so busy finishing the API doc rewrite I didn’t even open the archive file he sent me. I should be able to check for this during the day.

**Comment by MrPetovan** [comment]
Yep, same issue, the offending group and a contact of his have the same ID. @tobiasd please pull the latest develop and try to pull up the `DE` group again. The reason it wasn't showing up is because it has the same numeric ID as a contact that takes precedence. This has been fixed since.

**Comment by tobiasd** [comment]
It is still not showing up, I have to scroll down to see it as the list is hidden underneath the ACL dialogue box. For me the sorting order of the results is wrong. "DE" should be the first hit in the list, not hidden below entries like "Friendika Developers" that contain the letters *somewhereinbetween*.

**Comment by MrPetovan** [comment]
I still need an updated copy of your Javascript on the Composer page to run sorting tests with your exact setup.

**Comment by MrPetovan** [comment]
I got the updated copy, here's the result: #7959

**Comment by annando** [comment]
When selecting a forum account, the forum name should be added to the body.

**Comment by MrPetovan** [comment]
This is something that should happen in the post submission, the ACL selector isn't related to any post body, in some cases there is no body textarea input at all around it.

**Comment by annando** [comment]
For the future it would be great having two fields for the permissions for the "to" and the "cc" header. The "to" header would then add the persons to the body.

**Comment by MrPetovan** [comment]
I don't think so, `to` and `cc` are a protocol-level abstraction that we shouldn't expose because we aren't supporting only AP. We should provide for users' expectations, and I believe the current ACL field is providing for this, no matter what we end up cooking in the backend.

**Comment by annando** [comment]
I think we can close it now. We can create new issues when needed.
