### ISSUE TITLE
After applying the most recent updates, database errors.

### ISSUE THREAD

**Issue by 4nanook** [friendica/friendica#9600]
- [x] I have searched open and closed issues for duplicates

### Bug Description

After applying updates tonight, anything I try to save fails to save, comments, new posts.
### Steps to Reproduce

Apply updates, then try to post or comment.

Actual Result:
![friendica-pop-up](https://user-images.githubusercontent.com/3466797/100494383-fc1fdf00-30f5-11eb-9807-138fb8d4ed23.png)

It produces the above pop-up when I try to post or comment on a post.  It says it updated the database scheme without errors
but when I try to post with debugging enabled it produces the following in the logs:

2020-11-28T05:09:07Z worker [ERROR]: DB Error {"code":1927,"error":"Connection was killed","callstack":"DBA::selectFirst, Contact::selectFirst, User::getSystemAccount, HTTPSignature::fetchRaw, HTTPSignature::fetch, ActivityPub::fetchContent, APContact::getByURL, ActivityPub::probeProfile","params":"SELECT * FROM `contact` WHERE (`self` = 1 AND `uid` = 0) LIMIT 1"} - {"file":"Database.php","line":664,"function":"p","uid":"c2b47f","process_id":11657}
2020-11-28T05:09:07Z worker [ERROR]: DB Error {"code":2006,"error":"MySQL server has gone away","callstack":"Database::selectFirst, Config::get, JitConfig::get, User::getActorName, User::createSystemAccount, User::getSystemAccount, HTTPSignature::fetchRaw, HTTPSignature::fetch","params":"SELECT `v` FROM `config` WHERE (`cat` = 'system' AND `k` = 'actor_name') LIMIT 1"} - {"file":"Database.php","line":664,"function":"p","uid":"c2b47f","process_id":11657}
2020-11-28T05:09:07Z worker [ERROR]: DB Error {"code":2006,"error":"MySQL server has gone away","callstack":"DBA::count, Contact::removeDuplicates, Contact::updateContact, Contact::updateFromProbeArray, Contact::updateFromProbe, UpdateContact::execute, Worker::execFunction, Worker::execute","params":"SELECT COUNT(*) AS `count` FROM `contact` WHERE (`nurl` = 'http:\/\/friends.volkomorov.ru\/profile\/locutor99' AND `uid` = 0 AND `deleted` = 0 AND `network` IN ('dfrn', 'dspr', 'stat', 'apub'))"} - {"file":"Database.php","line":664,"function":"p","uid":"6ec393","process_id":9105}
2020-11-28T05:09:07Z worker [ERROR]: DB Error {"code":1927,"error":"Connection was killed","callstack":"DBA::exists, Probe::zot, Probe::detect, Probe::uri, Contact::updateFromProbe, UpdateContact::execute, Worker::execFunction, Worker::execute","params":"SELECT `nurl` FROM `gserver` WHERE (`nurl` = 'http:\/\/freefriends.online' AND `platform` IN ('hubzilla')) LIMIT 1"} - {"file":"Database.php","line":664,"function":"p","uid":"7450cd","process_id":10938}
2020-11-28T05:09:07Z worker [ERROR]: DB Error {"code":2006,"error":"MySQL server has gone away","callstack":"DBA::selectFirst, GServer::getID, Probe::uri, Contact::updateFromProbe, UpdateContact::execute, Worker::execFunction, Worker::execute, Worker::processQueue","params":"SELECT `id` FROM `gserver` WHERE (`nurl` = 'http:\/\/freefriends.online\/friendica') LIMIT 1"} - {"file":"Database.php","line":664,"function":"p","uid":"7450cd","process_id":10938}
2020-11-28T05:09:07Z worker [ERROR]: DB Error {"code":1927,"error":"Connection was killed","callstack":"DBA::selectFirst, Contact::updateAvatar, Contact::updateFromProbeArray, Contact::updateFromProbe, UpdateContact::execute, Worker::execFunction, Worker::execute, Worker::processQueue","params":"SELECT `uid`, `avatar`, `photo`, `thumb`, `micro`, `nurl`, `url`, `network` FROM `contact` WHERE (`id` = 2400 AND `self` = 0) LIMIT 1"} - {"file":"Database.php","line":664,"function":"p","uid":"ff1e03","process_id":10931}
2020-11-28T05:09:07Z worker [ERROR]: DB Error {"code":2006,"error":"MySQL server has gone away","callstack":"DBA::update, Contact::updateContact, Contact::updateFromProbeArray, Contact::updateFromProbe, UpdateContact::execute, Worker::execFunction, Worker::execute, Worker::processQueue","params":"UPDATE `contact` SET `name` = 'Eula Besser', `nick` = 'eula', `url` = 'https:\/\/friendica.kommune4.de\/profile\/eula', `addr` = 'eula@friendica.kommune4.de', `alias` = 'https:\/\/friendica.kommune4.de\/~eula', `keywords` = '', `location` = '', `about` = '', `batch` = '', `notify` = 'https:\/\/friendica.kommune4.de\/dfrn_notify\/eula', `poll` = 'https:\/\/friendica.kommune4.de\/dfrn_poll\/eula', `request` = 'https:\/\/friendica.kommune4.de\/dfrn_request\/eula', `confirm` = 'https:\/\/friendica.kommune4.de\/dfrn_confirm\/eula', `subscribe` = 'https:\/\/friendica.kommune4.de\/follow?url={uri}', `poco` = 'https:\/\/friendica.kommune4.de\/poco\/eula', `network` = 'dfrn', `manually-approve` = 1, `baseurl` = 'https:\/\/friendica.kommune4.de', `gsid` = 2063, `forum` = 0, `prv` = 0, `contact-type` = 0, `nurl` = 'http:\/\/friendica.kommune4.de\/profile\/eula', `updated` = '2020-11-28 05:09:06', `failed` = 0, `last-update` = '2020-11-28 05:09:06', `success_update` = '2020-11-28 05:09:06' WHERE (`id` = 2400)"} - {"file":"Database.php","line":767,"function":"e","uid":"ff1e03","process_id":10931}
2020-11-28T05:09:08Z worker [ERROR]: DB Error {"code":1927,"error":"Connection was killed","callstack":"DBA::selectFirst, GServer::getID, APContact::getByURL, ActivityPub::probeProfile, Probe::uri, Contact::updateFromProbe, UpdateContact::execute, Worker::execFunction","params":"SELECT `id` FROM `gserver` WHERE (`nurl` = 'http:\/\/pirati.ca') LIMIT 1"} - {"file":"Database.php","line":664,"function":"p","uid":"5a45aa","process_id":8059}
2020-11-28T05:09:08Z worker [ERROR]: DB Error {"code":2006,"error":"MySQL server has gone away","callstack":"DBA::selectFirst, GServer::check, GServer::getID, APContact::getByURL, ActivityPub::probeProfile, Probe::uri, Contact::updateFromProbe, UpdateContact::execute","params":"SELECT * FROM `gserver` WHERE (`nurl` = 'http:\/\/pirati.ca') LIMIT 1"} - {"file":"Database.php","line":664,"function":"p","uid":"5a45aa","process_id":8059}
2020-11-28T05:09:17Z worker [ERROR]: DB Error {"code":1927,"error":"Connection was killed","callstack":"DBA::selectFirst, Contact::selectFirst, User::getSystemAccount, HTTPSignature::fetchRaw, HTTPSignature::fetch, ActivityPub::fetchContent, APContact::getByURL, ActivityPub::probeProfile","params":"SELECT * FROM `contact` WHERE (`self` = 1 AND `uid` = 0) LIMIT 1"} - {"file":"Database.php","line":664,"function":"p","uid":"2013cb","process_id":8118}
2020-11-28T05:09:17Z worker [ERROR]: DB Error {"code":2006,"error":"MySQL server has gone away","callstack":"Database::selectFirst, Config::get, JitConfig::get, User::getActorName, User::createSystemAccount, User::getSystemAccount, HTTPSignature::fetchRaw, HTTPSignature::fetch","params":"SELECT `v` FROM `config` WHERE (`cat` = 'system' AND `k` = 'actor_name') LIMIT 1"} - {"file":"Database.php","line":664,"function":"p","uid":"2013cb","process_id":8118}
2020-11-28T05:14:29Z index [WARNING]: Invalid HTTP signature, message will be discarded. [] - {"file":"Receiver.php","line":113,"function":"processInbox","uid":"6f61b7","process_id":11714}
2020-11-28T05:20:43Z index [WARNING]: Invalid HTTP signature, message will be discarded. [] - {"file":"Receiver.php","line":113,"function":"processInbox","uid":"37697c","process_id":14247}
2020-11-28T05:21:33Z index [WARNING]: Invalid HTTP signature, message will be discarded. [] - {"file":"Receiver.php","line":113,"function":"processInbox","uid":"866024","process_id":14393}

There are no errors in the mysql logs and mysql is working fine for other applications like WordPress.

Expected Result:
Post and/or Comments to work.

### Platform Info

Friendica Version:

This is Friendica, version 2020.12-dev that is running at the web location https://friendica.eskimo.com. The database version is 1380/1380, the post update version is 1349/1349.
Friendica Source: 
Github
PHP version:
PHP 7.4.12 (cli) (built: Oct 31 2020 17:04:25) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.12, Copyright (c), by Zend Technologies

SQL version:
mysql  Ver 15.1 Distrib 10.3.25-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by 4nanook** [comment]
Everything was working fine until I applied updates, then it fails.

**Comment by annando** [comment]
Concerning the error 2006 I found this possible solution:
https://stackoverflow.com/questions/7942154/mysql-error-2006-mysql-server-has-gone-away

Just out of curiosity: Could you check if this setting does change something in the behaviour? https://github.com/friendica/friendica/pull/9599#issue-528562608

**Comment by 4nanook** [comment]
I set max_allowed_packet = 64M and restarted, no change.
Did I mention that everything else using MariaDB is still working fine?
Or that friendica was working fine until I applied updates then immediately thereafter did not work?

**Comment by annando** [comment]
Have you tried changing that PDO setting like I suggested in the comment above?

**Comment by 4nanook** [comment]
Are you referring to this:

o cope with this, we introduced a setting for the local.config.php some time ago:

	'database' => [
		'hostname' => 'hostname',
...
		'pdo_emulate_prepares' => true,
	],

     ... if so, then yes, no difference.

**Comment by annando** [comment]
With the last changes we implemented a lot of foreign keys. I guess that this puts more stress to the MySQL server. Possibly the server now reaches the limit of open files or something like that. You could check with a tool like mysqltuner.pl if the system reaches a limit.

**Comment by 4nanook** [comment]
I don't think it is a stress issue, it's not flakey, it's 100% fail but only on local post/comments.  Incoming messages still come fine.  mysqltuner didn't show any bottlenecks, zero slow queries, no resource exhausting.


 >>  MySQLTuner 1.7.13 - Major Hayden <major@mhtx.net>
 >>  Bug reports, feature requests, and downloads at http://mysqltuner.com/
 >>  Run with '--help' for additional options and output filtering

[--] Skipped version check for MySQLTuner script
[--] Performing tests on localhost:3306
[OK] Logged in using credentials passed on the command line
[OK] Currently running supported MySQL version 10.3.25-MariaDB-0ubuntu0.20.04.1
[OK] Operating on 64-bit architecture
 
-------- Log file Recommendations ------------------------------------------------------------------
[--] Log file: /var/log/mysql/error.log(46K)
[OK] Log file /var/log/mysql/error.log exists
[OK] Log file /var/log/mysql/error.log is readable.
[OK] Log file /var/log/mysql/error.log is not empty
[OK] Log file /var/log/mysql/error.log is smaller than 32 Mb
[!!] /var/log/mysql/error.log contains 2 warning(s).
[!!] /var/log/mysql/error.log contains 412 error(s).
[--] 2 start(s) detected in /var/log/mysql/error.log
[--] 1) 2020-11-28  4:17:45 0 [Note] /usr/sbin/mysqld: ready for connections.
[--] 2) 2020-11-28  2:47:08 0 [Note] /usr/sbin/mysqld: ready for connections.
[--] 2 shutdown(s) detected in /var/log/mysql/error.log
[--] 1) 2020-11-28  4:17:16 0 [Note] /usr/sbin/mysqld: Shutdown complete
[--] 2) 2020-11-28  2:47:07 0 [Note] /usr/sbin/mysqld: Shutdown complete
 
-------- Storage Engine Statistics -----------------------------------------------------------------
[--] Status: +Aria +CONNECT +CSV +InnoDB +MEMORY +MRG_MyISAM +MyISAM +PERFORMANCE_SCHEMA +SEQUENCE 
[--] Data in InnoDB tables: 4.1G (Tables: 1280)
[--] Data in MyISAM tables: 310.8M (Tables: 1099)
[--] Data in MEMORY tables: 0B (Tables: 2)
[OK] Total fragmented tables: 0
 
-------- Analysis Performance Metrics --------------------------------------------------------------
[--] innodb_stats_on_metadata: OFF
[OK] No stat updates during querying INFORMATION_SCHEMA.
 
-------- Security Recommendations ------------------------------------------------------------------
[OK] There are no anonymous accounts for any database users
[!!] User 'phpmyadmin@eskimo.com' has no password set.
[!!] User 'phpmyadmin@ftp.eskimo.com' has no password set.
[!!] User 'phpmyadmin@localhost' has no password set.
[!!] User 'phpmyadmin@shell.eskimo.com' has no password set.
[!!] User 'alpinist@%' does not specify hostname restrictions.
[!!] User 'phpbb@%' does not specify hostname restrictions.
[!!] User 'root@%' does not specify hostname restrictions.
[--] There are 618 basic passwords in the list.
 
-------- CVE Security Recommendations --------------------------------------------------------------
[OK] NO SECURITY CVE FOUND FOR YOUR VERSION
 
-------- Performance Metrics -----------------------------------------------------------------------
[--] Up for: 42m 16s (343K q [135.471 qps], 5K conn, TX: 454M, RX: 42M)
[--] Reads / Writes: 94% / 6%
[--] Binary logging is disabled
[--] Physical Memory     : 54.9G
[--] Max MySQL memory    : 50.7G
[--] Other process memory: 1.8G
[--] Total buffers: 10.6G global + 102.7M per thread (400 max threads)
[--] P_S Max memory usage: 0B
[--] Galera GCache Max memory usage: 0B
[OK] Maximum reached memory usage: 13.3G (24.18% of installed RAM)
[!!] Maximum possible memory usage: 50.7G (92.25% of installed RAM)
[OK] Overall possible memory usage with other process is compatible with memory available
[OK] Slow queries: 0% (0/343K)
[OK] Highest usage of available connections: 6% (27/400)
[OK] Aborted connections: 0.04%  (2/5517)
[!!] name resolution is active : a reverse name resolution is made for each new connection and can reduce performance
[!!] Query cache may be disabled by default due to mutex contention.
[OK] Query cache efficiency: 33.1% (147K cached / 443K selects)
[OK] Query cache prunes per day: 0
[OK] Sorts requiring temporary tables: 0% (8 temp sorts / 10K sorts)
[!!] Joins performed without indexes: 26
[OK] Temporary tables created on disk: 3% (513 on disk / 15K total)
[OK] Thread cache hit rate: 99% (27 created / 5K connections)
[OK] Table cache hit rate: 98% (2K open / 2K opened)
[OK] Open file limit used: 13% (2K/16K)
[OK] Table locks acquired immediately: 99% (6K immediate / 6K locks)
 
-------- Performance schema ------------------------------------------------------------------------
[--] Performance schema is disabled.
[--] Memory used by P_S: 0B
[--] Sys schema is installed.
 
-------- ThreadPool Metrics ------------------------------------------------------------------------
[--] ThreadPool stat is enabled.
[--] Thread Pool Size: 12 thread(s).
[--] Using default value is good enough for your version (10.3.25-MariaDB-0ubuntu0.20.04.1)
 
-------- MyISAM Metrics ----------------------------------------------------------------------------
[!!] Key buffer used: 20.8% (13M used / 67M cache)
[OK] Key buffer size / total MyISAM indexes: 64.0M/46.0M
[OK] Read Key buffer hit rate: 95.9% (106K cached / 4K reads)
[!!] Write Key buffer hit rate: 94.8% (650 cached / 616 writes)
 
-------- InnoDB Metrics ----------------------------------------------------------------------------
[--] InnoDB is enabled.
[--] InnoDB Thread Concurrency: 0
[OK] InnoDB File per table is activated
[OK] InnoDB buffer pool / data size: 10.0G/4.1G
[OK] Ratio InnoDB log file size / InnoDB Buffer pool size: 1.0G * 2/10.0G should be equal 25%
[!!] InnoDB buffer pool instances: 2
[--] Number of InnoDB Buffer Pool Chunk : 80 for 2 Buffer Pool Instance(s)
[OK] Innodb_buffer_pool_size aligned with Innodb_buffer_pool_chunk_size & Innodb_buffer_pool_instances
[OK] InnoDB Read buffer efficiency: 98.58% (11467507 hits/ 11632199 total)
[OK] InnoDB Write log efficiency: 94.72% (239671 hits/ 253042 total)
[OK] InnoDB log waits: 0.00% (0 waits / 13371 writes)
 
-------- AriaDB Metrics ----------------------------------------------------------------------------
[--] AriaDB is enabled.
[OK] Aria pagecache size / total Aria indexes: 128.0M/1B
[!!] Aria pagecache hit rate: 87.8% (3K cached / 449 reads)
 
-------- TokuDB Metrics ----------------------------------------------------------------------------
[--] TokuDB is disabled.
 
-------- XtraDB Metrics ----------------------------------------------------------------------------
[--] XtraDB is disabled.
 
-------- Galera Metrics ----------------------------------------------------------------------------
[--] Galera is disabled.
 
-------- Replication Metrics -----------------------------------------------------------------------
[--] Galera Synchronous replication: NO
[--] No replication slave(s) for this server.
[--] Binlog format: MIXED
[--] XA support enabled: ON
[--] Semi synchronous replication Master: OFF
[--] Semi synchronous replication Slave: OFF
[--] This is a standalone server
 
-------- Recommendations ---------------------------------------------------------------------------
General recommendations:
    Control warning line(s) into /var/log/mysql/error.log file
    Control error line(s) into /var/log/mysql/error.log file
    Set up a Password for user with the following SQL statement ( SET PASSWORD FOR 'user'@'SpecificDNSorIp' = PASSWORD('secure_password'); )
    Restrict Host for user@% to user@SpecificDNSorIp
    MySQL was started within the last 24 hours - recommendations may be inaccurate
    Reduce your overall MySQL memory footprint for system stability
    Configure your accounts with ip or subnets only, then update your configuration with skip-name-resolve=1
    Adjust your join queries to always utilize indexes
    Performance schema should be activated for better diagnostics
Variables to adjust:
  *** MySQL's maximum memory usage is dangerously high ***
  *** Add RAM before increasing MySQL buffer variables ***
    query_cache_size (=0)
    query_cache_type (=0)
    join_buffer_size (> 100.0M, or always use indexes with JOINs)
    performance_schema = ON enable PFS
    innodb_buffer_pool_instances(=10)

Server itself is not strained either:
 04:56:14 up 38 min,  1 user,  load average: 1.39, 1.37, 1.42
free -h
              total        used        free      shared  buff/cache   available
Mem:           54Gi       5.0Gi        43Gi        34Mi       6.9Gi        49Gi
Swap:            0B          0B          0B

Wordpress and everything else running on mariadb are not having any issues.

**Comment by 4nanook** [comment]
Since I had heard nothing more, I decided to try to do some troubleshooting on mysql (actually mariadb) and found some duplicate keys, but rebuilding the table in question (not related to friendica) did not resolve, and further showed it was an issue with 10.3, so I have upgraded to 10.5 which has gotten rid of the duplicate keys but there were many new conf items so I've gone to the default conf except for changing the bind address and I'm letting it accumulate some data before I run mysqltuner and fine tune things.  10.5 expanded the logging capability which may be helpful at pinning this down.  There were no errors printing under 10.3 but a few with 10.5 because of logging changes, in particular an explain option that decodes some things a bit.

**Comment by 4nanook** [comment]
Ok, shit just keeps getting weirder.  I've installed MariaD8 10.5.8, the latest:
mariadb  Ver 15.1 Distrib 10.5.8-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
I've got it tuned to where there are no errors, ZERO slow queries even though I've reduced slow queries from 10 seconds to 1 second, no resources exhausting at all.
I zero'd the logs so I'd be looking at fresh errors.  I have the specified debug code in index.php:
error_reporting(E_ERROR | E_WARNING | E_PARSE);
ini_set('error_log','php.out');
ini_set('log_errors','1');
ini_set('display_errors', '1');
I have logging enabled and set to warn.
Now, when I try a test post, I still get the same pop-up that I uploaded above BUT NOTHING shows up in friendica.log, NOTHING shows up in php.out, and when I grep my generic php log it also does not show any friendica errors.  I am at a loss.

**Comment by 4nanook** [comment]
I disabled all add-ons, still posts don't work, but things DO come in from the net, configuration changes DO work, nothing in friendica.log, nothing in php.out, nothing in my generic php error logs, and nothing in my mysql error logs and no slow queries.
I cleared my browser cache, active logins, cookies, and form and search history, no help.  I'm smack out of ideas here, please help! Also tried from Chrome in case it was something fuxored with Firefox, same results.  I tried to look at your change log file to see what had changed recently but get a 404 error.

**Comment by 4nanook** [comment]
I tried updating again, now I am getting some errors in the log but they appear to be irrelevant to the problem:

2020-11-29T08:15:12Z index [ERROR]: DB Error {"code":1406,"error":"Data too long for column 'k' at row 1","callstack":"Database::update, DatabaseCache::set, Images::getInfoFromURLCached, Media::fetchAdditionalData, Media::insert, Processor::storeAttachmentAsMedia, Processor::constructAttachList, Processor::createItem","params":"REPLACE `cache` (`k`, `v`, `expires`, `updated`) VALUES ('https:\/\/botusercontent.telegra.ph\/ifttt\/file\/eyJmIjoiQWdBQ0FnUUFBeDBDVWJRMmRBQUNFU1pmdzFoN1BZaG9TM1h1WWZuX1Y2ZUxJb0RzRGdBQ2M3TXhHNmhzSVZJR3FSUHVfb184WmRrbW55ZGRBQU1CQUFNQ0FBTjRBQU9QelFJQUFSNEUiLCJtIjoiaW1hZ2VcL2pwZWciLCJuIjoicGhvdG8uanBnIiwiZCI6MTYwNjYzNzY5Mn0\/3f5dadf3924b13c917\/photo.jpg', 'a:8:{i:0;i:620;i:1;i:775;i:2;i:2;i:3;s:24:\\\"width=\\\"620\\\" height=\\\"775\\\"\\\";s:4:\\\"bits\\\";i:8;s:8:\\\"channels\\\";i:3;s:4:\\\"mime\\\";s:10:\\\"image\/jpeg\\\";s:4:\\\"size\\\";i:106882;}', '2020-11-29 08:20:12', '2020-11-29 08:15:12')"} - {"file":"Database.php","line":767,"function":"e","uid":"bdf2ff","process_id":27923}
2020-11-29T08:16:07Z index [WARNING]: Invalid HTTP signature, message will be discarded. [] - {"file":"Receiver.php","line":113,"function":"processInbox","uid":"2a7f6a","process_id":28870}

I continue to receive incoming posts from other sites okay.

**Comment by 4nanook** [comment]
Following one of the suggestions on the forum I deleted Table 'friendica.tag-search-view' now getting errors complaining about it not existing in addition to the problems I already had.

**Comment by 4nanook** [comment]
As for database performance, if it were bottlenecked would my render times be like this:
Database: 0/0, Network: 0, Rendering: 0, Session: 0, I/O: 0, Other: 0.19, Total: 0.19

**Comment by annando** [comment]
When removing a view you have to recreate it again. Please call `bin/console dbstructure update -f`

**Comment by 4nanook** [comment]
Ok, did that BUT it still says "Item wasn't stored" in a brown and silver pop-up when I try to post or comment.  Everything else seems to work, nothing in friendica.log even though logging is turned on, nothing in php.out even though debugging code is in index.php, no errors in generic php log related to friendica and no errors in mysql (mariadb actually) logs, only normal start up notices.

**Comment by 4nanook** [comment]
Ok, I think I found the problem, upon turning the logging up to Debug, I get this notice:
2020-11-29T10:19:21Z index [NOTICE]: Author is blocked by user {"author-link":"https:\/\/friendica.eskimo.com\/profile\/nanook","uid":1,"item-uri":"https:\/\/friendica.eskimo.com\/objects\/a0
ad54dd-205f-c375-a975-84e454182449"} - {"file":"Item.php","line":3985,"function":"isAllowedByUser","uid":"fd3a49","process_id":46882}
So it looks like I've managed to block myself, fucking brilliant.  Now the question is how do I undo this?

**Comment by AlfredSK** [comment]
Just some hints...

> Maximum possible memory usage: 50.7G (**92.25%** of installed RAM)

You should really change this. This is dangerous! No wonder that you're running into trouble. On a standalone DB server this might be ok. But you need room for other services in memory. Change the settings to max. usage of around 50%.

> Total buffers: 10.6G global + 102.7M per thread

This setting is questionable. ;-) It should be the other way around. You should increase the InnoDB buffer pool but you should decease the 'join_buffer_size'. 100MB is insanely high! The default is 128K. It makes sense to set it higher. But not that high. For example my setting is 4MB.

**Comment by 4nanook** [comment]
It would take 100 connections to use that, AND there is plenty of swap
so it would just slow AND typically memory usage is only around 5GB, this is
NOT the problem.

  free -h
               total        used        free      shared  buff/cache   available
Mem:           54Gi       3.3Gi        45Gi        32Mi       6.1Gi        50Gi
Swap:            0B          0B          0B

      See actual usage at the moment only 3.3Gi, it gets up to 6-7 during peak
traffic hours, plently.

      The problem is based upon the logs:

2020-11-29T10:19:21Z index [NOTICE]: Author is blocked by user 
{"author-link":"https:\/\/friendica.eskimo.com\/profile\/nanook","uid":1,"item-uri":"https:\/\/friendica.eskimo.com\/objects\/a0ad54dd-205f-c375-a975-84e454182449"} 
- 
{"file":"Item.php","line":3985,"function":"isAllowedByUser","uid":"fd3a49","process_id":46882}

      I've managed to block myself.  Now if I can just figure out how to undo
that I should be fine.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by annando** [comment]
Although the problem might been triggered by some change in the Friendica code, I think it is something that needs to be checked on the MySQL side.

I just found this entry: https://www.psce.com/en/blog/2012/04/05/lost-connection-to-mysql-server-during-query/

Possibly you have got a short time out value for the communication to the MySQL server? Also you could try to avoid PDO and use the other MySQL class for PHP. This done by setting `disable_pdo` to `true` in the config.

**Comment by 4nanook** [comment]
Everything works except ME posting, other users can post, and the
log entry says author is blocked by user, but when I look at blocked list I'm
not on it, so not sure what is going on here.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by 4nanook** [comment]
That got rid of the message telling me the item wasn't stored, but it
didn't make it work.  The page does load about 3x faster that way.  But the
fact that it breaks error messages isn't good.

2020-11-29T10:33:36Z index [NOTICE]: Author is blocked by user 
{"author-link":"https:\/\/friendica.eskimo.com\/profile\/nanook","uid":1,"item-uri":"https:\/\/friendica.eskimo.com\/objects\/a0ad54dd-135f-c379-002b-46b134842417"} 
- 
{"file":"Item.php","line":3985,"function":"isAllowedByUser","uid":"5d6797","process_id":53251}
friendica@ftp:~/log$ grep 'Author is blocked by user' friendica.log
2020-11-29T10:19:21Z index [NOTICE]: Author is blocked by user 
{"author-link":"https:\/\/friendica.eskimo.com\/profile\/nanook","uid":1,"item-uri":"https:\/\/friendica.eskimo.com\/objects\/a0ad54dd-205f-c375-a975-84e454182449"} 
- 
{"file":"Item.php","line":3985,"function":"isAllowedByUser","uid":"fd3a49","process_id":46882}
2020-11-29T10:32:55Z index [NOTICE]: Author is blocked by user 
{"author-link":"https:\/\/friendica.eskimo.com\/profile\/nanook","uid":1,"item-uri":"https:\/\/friendica.eskimo.com\/objects\/a0ad54dd-545f-c378-d74b-2c3870433000"} 
- 
{"file":"Item.php","line":3985,"function":"isAllowedByUser","uid":"fce5d5","process_id":52944}
2020-11-29T10:33:36Z index [NOTICE]: Author is blocked by user 
{"author-link":"https:\/\/friendica.eskimo.com\/profile\/nanook","uid":1,"item-uri":"https:\/\/friendica.eskimo.com\/objects\/a0ad54dd-135f-c379-002b-46b134842417"} 
- 
{"file":"Item.php","line":3985,"function":"isAllowedByUser","uid":"5d6797","process_id":53251}



-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by 4nanook** [comment]
I've made so many changes and there is so much irrelevant data in this thread that I think perhaps it's best to start over since I no longer have the original configuration.
